#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000
set appimage_id $spawn_id

send -- "firejail --name=test --appimage hello-x86_64.AppImage\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"container firejail"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"NoNewPrivs 1"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"Seccomp 2"
}
after 500

puts "\nall done\n"
