#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

set appimage_id $spawn_id
send -- "firejail --name=test --appimage hello-x86_64.AppImage testfile\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"1 - testfile"
}

after 500
puts "\nall done\n"
