#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000
set appimage_id $spawn_id

send -- "firejail --trace --timeout=00:00:05 --appimage hello-x86_64.AppImage\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"AppRun:exec"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"AppRun:opendir"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Hello, World!"
}

after 500

puts "\nall done\n"
