#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --appimage \"bla;bla\"\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"is an invalid filename"
}
after 100

send -- "firejail --appimage /etc/shadow\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cannot read"
}
after 100

send -- "firejail --appimage appimage.sh\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "Error .*mounting appimage"
}
after 100




puts "\nall done\n"
