#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000


send -- "mkdir /sys/fs/cgroup/systemd/firejail\r"
sleep 1
send -- "ls /sys/fs/cgroup/systemd/firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"tasks"
}

send --  "firejail --name=\"join testing\" --cgroup=/sys/fs/cgroup/systemd/firejail/tasks\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "wc -l /sys/fs/cgroup/systemd/firejail/tasks\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"3"
}

spawn $env(SHELL)
send --  "firejail --join=\"join testing\"\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Switching to pid"
}
sleep 1
send -- "ps aux\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"/bin/bash"
}

after 100

spawn $env(SHELL)
send -- "wc -l /sys/fs/cgroup/systemd/firejail/tasks\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"3"
}
after 100

puts "\nall done\n"
