#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# start firemon
set firemon_id $spawn_id
send -- "firemon\r"
sleep 1

# start firejail
spawn $env(SHELL)
set firejail_id $spawn_id
send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}

# get messages on firemon
set spawn_id $firemon_id
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"exec"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"/bin/bash -c /bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"exec"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"fork"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"child"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"/bin/bash"
}
after 100

# exit firejail
set spawn_id $firejail_id
send -- "exit\r"
sleep 1

# get messages on firemon
set spawn_id $firemon_id
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"exit"
}

expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"EXIT SANDBOX"
}


puts "\nall done\n"
