#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firemon --interface\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"lo UP"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"10.10.20.1/29"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"10.10.50.1/24"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"br3"
}
sleep 1

puts "\n"
