#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000



send -- "firejail --version\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"git install support is disabled" { puts "TESTING: git support not available in current build\n"; exit}
	"git install support is enabled" { puts "git support available\n"}
}

set timeout 120
send -- "firejail --git-install\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Cloning into"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Configuration options"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"src/fseccomp/fseccomp default seccomp"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Mainline git Firejail version was installed in"
}
after 100

send -- "firejail --git-uninstall\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Cloning into"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Configuration options"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Firejail mainline git version uninstalled from"
}
after 100

puts "\nall done\n"
