#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 5
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=dhcpd /etc/init.d/isc-dhcp-server start\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --tree\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"root:/usr/sbin/dhcpd"
}
sleep 2

send -- "tail -n 200 /var/log/syslog\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Internet Systems Consortium DHCP Server"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Wrote 0 leases to leases file"
}
sleep 2

send -- "firejail --join=dhcpd\r"
sleep 2

send -- "ls /dev\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"tty0" {puts "TESTING ERROR 6\n";exit}
	"ttyS0" {puts "TESTING ERROR 6\n";exit}
	"ppp" {puts "TESTING ERROR 6\n";exit}
	"audio" {puts "TESTING ERROR 6\n";exit}
	"log"
}
sleep 2


puts "\nall done\n"
