#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 5
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=nginx /etc/init.d/nginx start\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2


spawn $env(SHELL)
send -- "firejail --tree\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"root::nginx: master process /usr/sbin/nginx"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"www-data::nginx: worker process"
}
sleep 2


send -- "rm index.html\r"
sleep 1
send -- "wget 127.0.0.1\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"saved"
}
send -- "cat index.html\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"DOCTYPE html PUBLIC"
}

sleep 1
send -- "rm index.html\r"

send -- "firejail --join=nginx\r"
sleep 2

send -- "ls /dev\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"tty0" {puts "TESTING ERROR 6\n";exit}
	"ttyS0" {puts "TESTING ERROR 6\n";exit}
	"audio" {puts "TESTING ERROR 6\n";exit}
	"ppp" {puts "TESTING ERROR 6\n";exit}
	"log"
}
sleep 1
send -- "ls -al /tmp;pwd\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"X11-unix" {puts "TESTING ERROR 11\n";exit}
	"/root"
}
sleep 2

puts "\nall done\n"
