#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --tmpfs=/var\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -l /var;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"total 0"
}
after 100
send -- "exit\r"
sleep 1

send -- "firejail --debug-check-filename --tmpfs=\"bla&&bla\"\r"
expect {
	timeout {puts "TESTING ERROR 13.1\n";exit}
	"Checking filename bla&&bla"
}
expect {
	timeout {puts "TESTING ERROR 13.2\n";exit}
	"Error:"
}
expect {
	timeout {puts "TESTING ERROR 13.3\n";exit}
	"is an invalid filename"
}
after 100


puts "\nall done\n"
