#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --private\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

send --  "ls -l /home\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"total 0"
}
after 100

send --  "ls -l /root\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"total 0"
}
after 100

send -- "exit\r"
after 100
puts "\nall done\n"
