#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

send -- "umount /proc\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Bad system call"
}

send -- "exit\r"
after 100
puts "\n"
