#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp=chown,fchown,fchownat,lchown --private\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

send -- "stty -echo\r"
after 100
send -- "touch testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"done"
}
after 100

send -- "ls -l testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"testfile"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"done"
}
after 100

send -- "chown netblue:netblue testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Bad system call"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"done"
}


send -- "exit\r"
after 100
puts "\nall done\n"
