#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "touch /mnt/firejail-test-file\r"
after 100
send -- "mkdir /mnt/firejail-test-dir\r"
after 100
send -- "touch /mnt/firejail-test-dir/firejail-test-file\r"
after 100
send -- "firejail --whitelist=/mnt/firejail-test-file --whitelist=/mnt/firejail-test-dir --debug\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find /mnt | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"4"
}
after 100
send -- "exit\r"
sleep 1


send -- "touch /opt/firejail-test-file\r"
after 100
send -- "mkdir /opt/firejail-test-dir\r"
after 100
send -- "touch /opt/firejail-test-dir/firejail-test-file\r"
after 100
send -- "firejail --whitelist=/opt/firejail-test-file  --whitelist=/opt/firejail-test-dir --debug\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find /opt | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"4"
}
after 100
send -- "exit\r"
sleep 1

send -- "touch /media/firejail-test-file\r"
after 100
send -- "mkdir /media/firejail-test-dir\r"
after 100
send -- "touch /media/firejail-test-dir/firejail-test-file\r"
after 100
send -- "firejail --whitelist=/media/firejail-test-file --whitelist=/media/firejail-test-dir --debug\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find /media | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"4"
}
after 100
send -- "exit\r"
sleep 1


send -- "firejail --whitelist=/var/run --whitelist=/var/lock --debug\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find /var | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	""
}
after 100
send -- "exit\r"
sleep 1

send -- "touch /srv/firejail-test-file\r"
after 100
send -- "mkdir /srv/firejail-test-dir\r"
after 100
send -- "touch /srv/firejail-test-dir/firejail-test-file\r"
after 100
send -- "firejail --whitelist=/srv/firejail-test-file --whitelist=/srv/firejail-test-dir --debug\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find /srv | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"4"
}
after 100
send -- "exit\r"


after 100
puts "\nall done\n"
