#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# check eth0
send -- "firejail --net=br0 --net=br1 --net=br2 --net=br3\r"
expect {
	timeout {puts "TESTING ERROR 0.0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"10.10.20"
}
expect {
	timeout {puts "TESTING ERROR 0.2\n";exit}
	"255.255.255.248"
}
expect {
	timeout {puts "TESTING ERROR 0.3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 0.4\n";exit}
	"Child process initialized"
}
sleep 2
send -- "exit\r"
sleep 2

# check eth1
send -- "firejail --net=br0 --net=br1 --net=br2 --net=br3\r"
expect {
	timeout {puts "TESTING ERROR 1.0\n";exit}
	"eth1"
}
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"10.10.30"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"Child process initialized"
}
sleep 2
send -- "exit\r"
sleep 2


# check eth2
send -- "firejail --net=br0 --net=br1 --net=br2 --net=br3\r"
expect {
	timeout {puts "TESTING ERROR 2.0\n";exit}
	"eth2"
}
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"10.10.40"
}
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 2.3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 2.4\n";exit}
	"Child process initialized"
}
sleep 2
send -- "exit\r"
sleep 2



# check eth3
send -- "firejail --net=br0 --net=br1 --net=br2 --net=br3\r"
expect {
	timeout {puts "TESTING ERROR 3.0\n";exit}
	"eth3"
}
expect {
	timeout {puts "TESTING ERROR 3.1\n";exit}
	"10.10.50"
}
expect {
	timeout {puts "TESTING ERROR 3.2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 3.3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 2
send -- "exit\r"
sleep 2




# check loopback
send -- "firejail --net=br0 --net=br1 --net=br2 --net=br3\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"127.0.0.1"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"255.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}

# check default gateway
send -- "bash\r"
sleep 1
send -- "netstat -rn;pwd\r"
expect {
	timeout {puts "TESTING ERROR 10.1\n";exit}
	"0.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 10.2\n";exit}
	"10.10.20.1"
}
expect {
	timeout {puts "TESTING ERROR 10.3\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 10.4\n";exit}
	"10.10.20.0"
}
expect {
	timeout {puts "TESTING ERROR 10.5\n";exit}
	"0.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 10.6\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"home"
}
sleep 1

puts "\n"

