#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# blacklist a directory symlink
send -- "firejail --blacklist=auto2\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls auto2\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cannot open directory"
}
send -- "exit\r"
sleep 1

# blacklist a directory symlink from a profile file
send -- "firejail --profile=blacklist3.profile\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls auto2\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"cannot open directory"
}
send -- "exit\r"
sleep 1

# do not blacklist /bin
send -- "firejail --blacklist=auto3\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"auto3 directory link was not blacklisted"
}
expect {
	timeout {puts "TESTING ERROR 5.1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls auto3; pwd\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"cannot open directory" {puts "TESTING ERROR 6.1\n";exit}
	"home"
}
send -- "exit\r"
sleep 1

# do not blacklist /usr/bin
send -- "firejail --blacklist=auto3\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"auto3 directory link was not blacklisted"
}
expect {
	timeout {puts "TESTING ERROR 7.1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls auto3; pwd\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"cannot open directory" {puts "TESTING ERROR 9.1\n";exit}
	"home"
}
send -- "exit\r"
sleep 1


puts "all done\n"

