#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug ls -al\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/generic.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Starting ls -al"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"parent is shutting down, bye"
}
sleep 1

puts "\nall done\n"

