#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug /usr/bin/firefox www.gentoo.org\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/firefox.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Starting /usr/bin/firefox"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 5

puts "\n"

