#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=bingo1 --caps\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo2\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo3 --caps.drop=all\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo4 --caps.drop=chown,kill\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo5 --caps.keep=chown,kill\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo6 --profile=caps1.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=bingo7 --profile=caps2.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1




spawn $env(SHELL)
send -- "firemon --caps\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"bingo1"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"31cffff"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"bingo2"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"fffffff"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"bingo3"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"000000000000"
}

expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"bingo4"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"ffffffde"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"bingo5"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"0000000000000021"
}

expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"bingo6"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"ffffffde"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"bingo7"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"0000000000000021"
}







sleep 1

puts "\n"

