#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=br0\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "find /sys | grep --color=never eth0;pwd\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"/sys/class/net/eth0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"home"
}
sleep 1

send -- "find /sys | grep --color=never br0;pwd\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"/sys/class/net/br0" {puts "TESTING ERROR 5\n";exit}
	"home"
}
sleep 1

puts "\n"

