#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# dir
send -- "firejail --net=br0 --output=fscheck-dir\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --output=../test/fscheck-dir\r"
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"Error"
}
after 100

# dir link
send -- "firejail --net=br0 --output=fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --output=../test/fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Error"
}
after 100

# file link
send -- "firejail --net=br0 --output=fscheck-file-link\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --output=../test/fscheck-file-link\r"
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"Error"
}
after 100

# hard link1
send -- "firejail --net=br0 --output=fscheck-file-hard1\r"
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"Error"
}
after 100

# hard link2
send -- "firejail --net=br0 --output=fscheck-file-hard2\r"
expect {
	timeout {puts "TESTING ERROR 2.3\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --output=../test/fscheck-file-hard1\r"
expect {
	timeout {puts "TESTING ERROR 2.4\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --output=../test/fscheck-file-hard2\r"
expect {
	timeout {puts "TESTING ERROR 2.5\n";exit}
	"Error"
}
after 100




# no file
send -- "firejail --net=br0 --output=../test/nofile\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Error"
}
after 100

# real GID/UID
send -- "firejail --net=br0 --output=/etc/shadow\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error"
}
after 100
