#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# dir
#send -- "firejail --net=br0 --chroot=fscheck-dir\r"
#expect {
#	timeout {puts "TESTING ERROR 0\n";exit}
#	"Error"
#}
#after 100

# ..
send -- "firejail --net=br0 --chroot=../test/fscheck-dir\r"
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"Error"
}
after 100

# dir link
send -- "firejail --net=br0 --chroot=fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --chroot=../test/fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Error"
}
after 100

# file link
send -- "firejail --net=br0 --chroot=fscheck-file-link\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error"
}
after 100

# file
send -- "firejail --net=br0 --chroot=fscheck-file\r"
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --chroot=../test/fscheck-file\r"
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"Error"
}
after 100

# no file
send -- "firejail --net=br0 --chroot=../test/nodir\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Error"
}
after 100

# same owner
#send -- "firejail --net=br0 --chroot=/etc\r"
#expect {
#	timeout {puts "TESTING ERROR 4\n";exit}
#	"Error"
#}
#after 100
