#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# dir
send -- "firejail --net=br0 --shell=fscheck-dir\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --shell=../test/fscheck-dir\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Error"
}
after 100

# dir link
send -- "firejail --net=br0 --shell=fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --net=br0 --shell=../test/fscheck-dir-link\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Error"
}
after 100

# file link
#send -- "firejail --net=br0 --shell=fscheck-file-link\r"
#expect {
#	timeout {puts "TESTING ERROR 4\n";exit}
#	"Error"
#}
#after 100

# ..
send -- "firejail --net=br0 --shell=../test/fscheck-file-link\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Error"
}
after 100

# no file
send -- "firejail --net=br0 --shell=../test/nofile\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Error"
}
after 100

# real GID/UID
send -- "firejail --net=br0 --shell=/etc/shadow\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Error"
}
after 100
