#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --tracelog icedove\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/icedove.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 5

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 3.1\n";exit}
	"icedove"
}
sleep 1

send -- "firejail --name=blablabla\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firemon --seccomp\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	":firejail --tracelog icedove"
}
expect {
	timeout {puts "TESTING ERROR 5.1 (seccomp)\n";exit}
	"Seccomp:	2"
}
expect {
	timeout {puts "TESTING ERROR 5.1\n";exit}
	"name=blablabla"
}
sleep 1
send -- "firemon --caps\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	":firejail --tracelog icedove"
}
expect {
	timeout {puts "TESTING ERROR 6.1\n";exit}
	"CapBnd:"
}
expect {
	timeout {puts "TESTING ERROR 6.2\n";exit}
	"0000000000000000"
}
expect {
	timeout {puts "TESTING ERROR 6.3\n";exit}
	"name=blablabla"
}
sleep 1

puts "\nall done\n"

