#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --profile=ignore.profile --ignore=seccomp \r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error: please use --profile after --include"
}

send -- "firejail --debug --ignore=seccomp\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	BLACKLIST {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
sleep 1
send -- "exit\r"
sleep 1

send -- "firejail --ignore=seccomp --ignore=shell --profile=ignore.profile \r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ps aux | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"4"
}
sleep 1


puts "\nall done\n"
