#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug --noprofile --net=br0 --ip6=2001:0db8:0:f101::1/64 --netfilter6=ipv6.net\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Installing network filter"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"DROP"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"2001:db8:1f0a:3ec::2"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
sleep 2

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"inet6"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"2001:db8:0:f101::1"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Scope:Global" { puts "Debian\n"}
	"scopeid 0x0<global>" { puts "Arch\n"}
}


puts "\nall done\n"

