#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "cat /dev/kmsg\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Permission denied"
}
sleep 1

send -- "cat /proc/kmsg\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Permission denied"
}
sleep 1

puts "\nall done\n"

