#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "ssh bingo@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"password:" {
		puts "\nTESTING: please enter SSH password"
		set oldmode [stty -echo -raw]
		expect_user -re "(.*)\n"
		send_user "\n"
		eval stty $oldmode
#		stty echo
		set pass $expect_out(1,string)
		send -- "$pass\r"
		puts "TESTING: password sent to the server"
	}	
	"Child process initialized"
}
sleep 1

# test default gw
send -- "bash\r"
sleep 1
send -- "ps aux; pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"bash"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"ps aux"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"home"
}
sleep 1


send -- "ps aux |wc -l; pwd\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"5"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"home"
}
sleep 1

puts "\n"
