#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --noprofile --debug\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Using the local network stack"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 2
send -- "exit\r"
sleep 2

# check loopback
send -- "firejail --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"127.0.0.1"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"255.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"UP"
}

puts "all done\n"

