#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=none\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0" {puts "TESTING ERROR 0.1\n";exit}
	"Child process initialized"
}
sleep 1

# test default gw
send -- "bash\r"
sleep 1
send -- "netstat -rn; pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0.0.0.0" {puts "TESTING ERROR 1.1\n";exit}
	"home"
}
sleep 1

# check again devices
send -- "cat /proc/1/net/dev;pwd\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"eth0" {puts "TESTING ERROR 2.1\n";exit}
	"home"
}
sleep 1


puts "\n"
