#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --net=br0 --ip=10.10.20.5 --defaultgw=10.10.20.2\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.20.5"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.248"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}

# check default gateway
send -- "bash\r"
sleep 1
send -- "netstat -rn;pwd\r"
expect {
	timeout {puts "TESTING ERROR 10.1\n";exit}
	"0.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 10.2\n";exit}
	"10.10.20.2"
}
expect {
	timeout {puts "TESTING ERROR 10.3\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 10.4\n";exit}
	"10.10.20.0"
}
expect {
	timeout {puts "TESTING ERROR 10.5\n";exit}
	"0.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 10.6\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"home"
}
sleep 1

puts "\n"

