#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --trace\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1:bash:open /dev/tty"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"1:bash:fopen /etc/passwd"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"1:bash:access /etc/terminfo/x/xterm"
}

sleep 1

puts "all done\n"
