#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

set firstspawn $spawn_id

send --  "firejail --name=shutdowntesting ./catchsignal2.sh\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send --  "firejail --shutdown=shutdowntesting\r"

set spawn_id $firstspawn
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"2"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"3"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"4"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"5"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"10"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	"20"
}
expect {
	timeout {puts "TESTING ERROR 30\n";exit}
	"30"
}
expect {
	timeout {puts "TESTING ERROR 40\n";exit}
	"40"
}
expect {
	timeout {puts "TESTING ERROR 50\n";exit}
	"50"
}
expect {
	timeout {puts "TESTING ERROR 60\n";exit}
	"Killed"
}
sleep 1

puts "\nalldone\n"
