#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=shutdowntesting\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 3

spawn $env(SHELL)
send --  "firejail --shutdown=shutdowntesting;pwd\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"home"
}
sleep 1

send --  "firejail --list;pwd\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"shutdowntesting" {puts "TESTING ERROR 6\n";exit}
	"home"
}
sleep 1

puts "\nalldone\n"
