#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --trace\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"bash:open /dev/tty" {puts "64bit\n"}
	"bash:open64 /dev/tty" {puts "32bit\n"}
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"bash:fopen /etc/passwd"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"bash:access /etc/terminfo/x/xterm" {puts "debian\n"}
	"bash:access /usr/share/terminfo/x/xterm" {puts "arch\n"}
}

sleep 1

puts "\nall done\n"
