#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --trace firefox --name=testing\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"command not found" {puts "\nTESTING: not tested, firefox not found\n"; exit}
	"1:firefox:open" {puts "\n"}
	"1:iceweasel:open"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"1:firefox:access" {puts "\n"}
	"1:iceweasel:access"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"1:firefox:connect" {puts "\n"}
	"1:iceweasel:connect"
}

sleep 1

puts "\n"
