#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --blacklist=/var\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /var;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"home"
}
send -- "cd /var;pwd\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"home"
}
sleep 1

puts "\n"

