#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --profile=name.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 3

spawn $env(SHELL)
send --  "firejail --join=jointesting;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Switching to pid"
}
sleep 3


spawn $env(SHELL)
send --  "firejail --shutdown=jointesting;pwd\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"home"
}
sleep 5

send --  "firejail --list;pwd\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"jointesting" {puts "TESTING ERROR 5\n";exit}
	"home"
}
sleep 1

puts "\nall done\n"
