#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --tmpfs=/var\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /var;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"total 0"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"/root"
}
sleep 1
send -- "exit\r"
sleep 2

send -- "firejail --debug-check-filename --tmpfs=\"bla&&bla\"\r"
expect {
	timeout {puts "TESTING ERROR 13.1\n";exit}
	"Checking filename bla&&bla"
}
expect {
	timeout {puts "TESTING ERROR 13.2\n";exit}
	"Error:"
}
expect {
	timeout {puts "TESTING ERROR 13.3\n";exit}
	"is an invalid filename"
}
after 100


puts "\nalldone\n"

