#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

# test processes
send -- "bash\r"
sleep 1
send -- "ps aux; pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"bash"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"ps aux"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"home"
}
sleep 1


send -- "ps aux |wc -l; pwd\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"6" {puts "normal system\n'}
	"5" {puts "grsecurity\n"}
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"home"
}
sleep 1

puts "\nall done\n"
