#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --whitelist=/tmp/.X11-unix\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -al /tmp\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	".X11-unix"
}
sleep 1

send -- "ls -a /tmp | wc\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"3"
}
sleep 1

send -- "ls -a ~ | wc\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"4"
}

sleep 1
puts "\nall done\n"

