#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "mkdir /tmp/firejailtestdir\r"
sleep 1
send -- "ls > /tmp/firejailtestdir/tmpfile\r"
sleep 1

send -- "firejail --profile=tmpfs.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}

# testing private only
send -- "bash\r"
sleep 1

send -- "ls -l /tmp/firejailtestdir;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"tmpfile" {puts "TESTING ERROR 1\n";exit}
	"home"
}
sleep 1
send -- "exit\r"
sleep 1
send -- "exit\r"
sleep 1
send -- "rm -fr  /tmp/firejailtestdir\r"

sleep 1

puts "\n"
