#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp=\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --seccomp.drop=\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --seccomp.keep=\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --profile=seccomp-bad-empty.profile\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Error: line 1 in the custom profile is invalid"
}

send --  "firejail --profile=seccomp-bad-empty2.profile\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Error: line 1 in the custom profile is invalid"
}
sleep 1
puts "\n"

