#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --seccomp.print=test\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"EXAMINE_SYSCAL"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"init_module"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"delete_module"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"RETURN_ALLOW"
}
sleep 1
puts "\nall done\n"
