#!/usr/bin/expect -f

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "firejail --trace mkdir ttt\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1:mkdir:mkdir ttt"
}
sleep 1

send -- "firejail --trace rmdir ttt\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"1:rmdir:rmdir ttt"
}
sleep 1

send -- "firejail --trace touch ttt\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"1:touch:open ttt" {puts "OK\n";}
	"1:touch:open64 ttt" {puts "OK\n";}
}
sleep 1

send -- "firejail --trace rm ttt\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"1:rm:unlinkat ttt"
}
sleep 1

send -- "firejail --trace wget -q debian.org\r"
expect {
	timeout {puts "TESTING ERROR 8.1\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 8.2\n";exit}
	"1:bash:open /dev/tty" {puts "OK\n";}
	"1:bash:open64 /dev/tty" {puts "OK\n";}
}
expect {
	timeout {puts "TESTING ERROR 8.3\n";exit}
	"1:wget:fopen64 /etc/wgetrc" {puts "OK\n";}
	"1:wget:fopen /etc/wgetrc"  {puts "OK\n";}
}
expect {
	timeout {puts "TESTING ERROR 8.4\n";exit}
	"1:wget:fopen /etc/hosts"
}
expect {
	timeout {puts "TESTING ERROR 8.5\n";exit}
	"1:wget:connect"
}
expect {
	timeout {puts "TESTING ERROR 8.6\n";exit}
	"1:wget:fopen64 index.html" {puts "OK\n";}
	"1:wget:fopen index.html" {puts "OK\n";}
}
sleep 1

send -- "firejail --trace rm index.html\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"1:rm:unlinkat index.html"
}
sleep 1


puts "\n"

