#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail wine --help\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/wine.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Usage: wine PROGRAM"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"wine --version"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"parent is shutting down, bye..."
}

puts "\nall done\n"

