#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# start a bash session
send --  "firejail --apparmor=test-profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

# ... and try to run a local program
send --  "./a.out --help\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"denied" {puts "TESTING ERROR 2\n";exit}
	"Usage: ./a.out"
}
after 500
puts "\nall done\n"
