#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --name=joinrun\r"
sleep 2

spawn $env(SHELL)
send --  "./joinrun.sh\r"
expect {
	timeout {puts "TESTING ERROR 3.1.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.1.2\n";exit}
	"#arg1#"
}
expect {
	timeout {puts "TESTING ERROR 3.1.3\n";exit}
	"#arg2#"
}

expect {
	timeout {puts "TESTING ERROR 3.2.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.2.2\n";exit}
	"#arg1 tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.2.3\n";exit}
	"#arg2 tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.3.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.3.2\n";exit}
	"#arg1 tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.3.3\n";exit}
	"#arg2 tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.4.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.4.2\n";exit}
	"#arg1 tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.4.3\n";exit}
	"#arg2 tail#"
}

expect {
	timeout {puts "TESTING ERROR 3.5.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.5.2\n";exit}
	"#arg1&tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.5.3\n";exit}
	"#arg2&tail#"
}

expect {
	timeout {puts "TESTING ERROR 3.6.1\n";exit}
	"Arguments:"
}
expect {
	timeout {puts "TESTING ERROR 3.6.2\n";exit}
	"#arg1&tail#"
}
expect {
	timeout {puts "TESTING ERROR 3.6.3\n";exit}
	"#arg2&tail#"
}

puts "\nall done\n"
