#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "rm index.html*\r"
after 500

send -- "firejail gzip -c ../../mkdeb.sh | firejail gunzip -c\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"This file is part of Firejail project"
}
after 500

puts "\nall done\n"
