#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "rm index.html*\r"
after 500

send -- "firejail --ignore=quiet wget -q debian.org\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Parent is shutting down"
}
after 100

send -- "ls -l index.html\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"No such file or directory" {puts "TESTING ERROR 4\n";exit}
	"rw"
}
after 100
send -- "rm index.html*\r"
after 500

puts "\nall done\n"
