#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 60
spawn $env(SHELL)
match_max 100000

send -- "/usr/bin/xz -c /usr/bin/firejail > firejail_t1\r"
sleep 1

send -- "firejail /usr/bin/xz -c /usr/bin/firejail > firejail_t2\r"
sleep 1

send -- "md5sum firejail_t1 firejail_t2; ls -l firejail_t1 firejail_t2\r"
sleep 1

send -- "diff -s firejail_t1 firejail_t2\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"firejail_t1 and firejail_t2 are identical"
}

send -- "rm firejail_t*\r"
sleep 1


puts "\nall done\n"
