#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --net=br0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --bandwidth=test status\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"qdisc noqueue 0: dev eth0"
}
sleep 1

send -- "firejail --bandwidth=test set br0 50 10\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Configuring interface eth0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"configuring tc ingress"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"configuring tc egress"
}

send -- "firejail --bandwidth=test status\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"dev eth0"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"rate 80Kbit burst 10Kb"
}
sleep 1

send -- "firejail --bandwidth=test clear br0\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Removing bandwith limits"
}
sleep 1

send -- "firejail --bandwidth=test status; pwd\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"rate 80Kbit burst 10Kb" {puts "TESTING ERROR 9\n";exit}
	"home" {puts "ok\n"}
}
sleep 1

puts "\nall done\n"
