#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=test --net=br0 --dns=1.2.3.4 --dns=2.3.4.5 --dns=3.4.5.6\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --dns.print=test\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"nameserver 1.2.3.4"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"nameserver 2.3.4.5"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"nameserver 3.4.5.6"
}

after 500

puts "\nall done\n"
