#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --net=br0 --ip=10.10.20.50\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send -- "firemon --interface\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"firejail --name=test --net=br0 --ip=10.10.20.50"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"eth0 UP, 10.10.20.50/24"
}
sleep 2
puts "\nall done\n"
