#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=eth0 --name=test1\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --net=eth0 --name=test2\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firemon --interface\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Link status"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"lo UP"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"eth0-"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"IPv4 status"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"lo UP"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"eth0-"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"IPv6 status"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"lo UP"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"eth0-"
}

after 100

puts "\n"
