#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=test1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=test2\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firemon --route\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"name=test1"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"0.0.0.0/0 via 192.168.1.1, dev eth0, metric 0" {puts "Debian testing\n";}
	"0.0.0.0/0 via 192.168.1.1, dev enp0s3, metric 1024" {puts "Centos 7 testing\n";}
	"0.0.0.0/0 via 192.168.1.1, dev enp0s3, metric 0" {puts "OpenSUSE testing\n";}
            "0.0.0.0/0 via 192.168.1.1, dev enp0s3, metric 100" {puts "Arch testing\n";}
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"10.10.30.0/24, dev br1, scope link src 10.10.30.1"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"10.10.50.0/24, dev br3, scope link src 10.10.50.1"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"name=test2"
}
after 100

puts "\nalldone\n"
