#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --hostname=bingo --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1
send -- "stty -echo\r"
after 100

send -- "ping -c 3 bingo; echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"3 packets transmitted, 3 received"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"done"
}
send -- "exit\r"
after 100

puts "all done\n"
