#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --noprofile --net=br0 --ip6=2001:0db8:0:f101::1/64 ip addr show\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"inet6"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"2001:db8:0:f101::1/64"
}
sleep 1

send -- "firejail --profile=ip6.profile ip addr show\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"inet6"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"2001:db8:0:f101::1/64"
}
after 500
puts "\nall done\n"
exit
