#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=br1 --iprange=10.10.30.50,10.10.30.55\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.30.50" {puts "10.10.30.50\n"}
	"10.10.30.51" {puts "10.10.30.51\n"}
	"10.10.30.52" {puts "10.10.30.52\n"}
	"10.10.30.53" {puts "10.10.30.53\n"}
	"10.10.30.54" {puts "10.10.30.54\n"}
	"10.10.30.55" {puts "10.10.30.55\n"}
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "exit\r"
sleep 1

send -- "firejail --profile=iprange.profile\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"10.10.30.50" {puts "10.10.30.50\n"}
	"10.10.30.51" {puts "10.10.30.51\n"}
	"10.10.30.52" {puts "10.10.30.52\n"}
	"10.10.30.53" {puts "10.10.30.53\n"}
	"10.10.30.54" {puts "10.10.30.54\n"}
	"10.10.30.55" {puts "10.10.30.55\n"}
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "exit\r"
sleep 1



send -- "firejail --iprange=10.10.30.50,10.10.30.55\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"no network device configured"
}
after 100

send -- "firejail --net=br1 --iprange=10.10.30.50,10.10.30.55 --iprange=10.10.30.50,10.10.30.55\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"cannot configure the IP range twice for the same interface"
}
after 100

send -- "firejail --net=br1 --iprange=10.10.30.50\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"invalid IP range"
}
after 100

send -- "firejail --net=br0 --iprange=10.10.30.50,10.10.30.55\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"IP range addresses not in network range"
}
after 100

send -- "firejail --net=br1 --iprange=10.10.30.55,10.10.30.50\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"invalid IP range"
}
after 100


after 100

puts "\nall done\n"
