# Generated by ip6tables-save v1.4.14 on Wed Jan 13 10:53:40 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -s 2001:db8:1f0a:3ec::2/128 -j DROP
COMMIT
# Completed on Wed Jan 13 10:53:40 2016
