#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=br0  cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.20."
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Default gateway 10.10.20.1"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo:"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"eth0:"
}
after 500

send -- "firejail --net=br0 --ip=10.10.20.5 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"10.10.20.5"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Default gateway 10.10.20.1"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "firejail --net=br0 --ip=10.10.50.5 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"the IP address is not in the interface range"
}
after 500

send -- "firejail --net=br0  --defaultgw=10.10.20.2 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Default gateway 10.10.20.2"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "firejail --net=br0  --defaultgw=10.110.210.2 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"default gateway 10.110.210.2 is not in the range of any network"
}
after 500




after 100
puts "\nall done\n"
