#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=br0  cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.20."
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Default gateway 10.10.20.1"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo:"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"eth0:"
}
after 500

send -- "firejail --net=br0 --ip=10.10.20.5 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"10.10.20.5"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Default gateway 10.10.20.1"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "firejail --net=br0 --ip=10.10.50.5 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"the IP address is not in the interface range"
}
after 500

send -- "firejail --net=br0  --defaultgw=10.10.20.2 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Default gateway 10.10.20.2"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "firejail --net=br0  --defaultgw=10.110.210.2 cat /proc/1/net/dev\r"
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"default gateway 10.110.210.2 is not in the range of any network"
}
after 500

send -- "firejail --noprofile --net=br0 --ip=none ip addr show\r"
expect {
	timeout {puts "TESTING ERROR 17\n";exit}
	"eth0" {puts "TESTING ERROR 18\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 19\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	"inet " {puts "TESTING ERROR 21\n";exit}
	"inet6"
}
after 500

send -- "firejail --net=br0 --mtu=1000 --noprofile ip link show\r"
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	"mtu 1000"
}
expect {
	timeout {puts "TESTING ERROR 25\n";exit}
	"state UP"
}

after 500

send -- "firejail --profile=net_ip.profile ip addr show\r"
expect {
	timeout {puts "TESTING ERROR 26\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 27\n";exit}
	"00:11:22:33:44:55"
}
expect {
	timeout {puts "TESTING ERROR 28\n";exit}
	"10.10.20.55"
}
expect {
	timeout {puts "TESTING ERROR 29\n";exit}
	"Default gateway 10.10.20.9"
}
expect {
	timeout {puts "TESTING ERROR 30\n";exit}
	"00:11:22:33:44:55"
}
expect {
	timeout {puts "TESTING ERROR 31\n";exit}
	"10.10.20.55"
}
after 500

send -- "firejail --profile=net_ip.profile ip route  show\r"
expect {
	timeout {puts "TESTING ERROR 32\n";exit}
	"default via 10.10.20.9"
}
expect {
	timeout {puts "TESTING ERROR 33\n";exit}
	"10.10.20.0/24 dev eth0 proto kernel scope link src 10.10.20.55"
}
after 500


puts "\nall done\n"
