#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --net=br0 --net=br1 --defaultgw=10.10.30.89 --protocol=unix,inet,netlink\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth1"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 1

# check default gateway
send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 10.1\n";exit}
	"default via 10.10.30.89 dev eth1"
}

send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 10.2\n";exit}
	"10.10.20.0/29 dev eth0  proto kernel  scope link" {puts "old iproute2\n";}
	"10.10.20.0/29 dev eth0 proto kernel scope link" {puts "new iproute2\n";}
}

send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 10.3\n";exit}
	"10.10.30.0/24 dev eth1  proto kernel  scope link" {puts "old iproute2\n";}
	"10.10.30.0/24 dev eth1 proto kernel scope link" {puts "new iproute2\n";}
}
send -- "exit\r"
after 100

puts "\nall done\n"
