#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --net=br0 --ip=10.10.20.5\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.20.5"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.248"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1
send -- "exit\r"
sleep 1

# check loopback
send -- "firejail --net=br0 --ip=10.10.20.5 --protocol=unix,inet,netlink\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"127.0.0.1"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"255.0.0.0"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

# check default gateway
send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 10.1\n";exit}
	"default via 10.10.20.1 dev eth0"
}

send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"10.10.20.0/29 dev eth0  proto kernel  scope link" {puts "old iproute2\n";}
	"10.10.20.0/29 dev eth0 proto kernel scope link" {puts "new iproute2\n";}
}
send -- "exit\r"
after 100

puts "\n"
