#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# check eth0
send -- "firejail --profile=net-profile.profile\r"
expect {
	timeout {puts "TESTING ERROR 0.0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"00:11:22:33:44:55"
}
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"10.10.20"
}
expect {
	timeout {puts "TESTING ERROR 0.2\n";exit}
	"255.255.255.248"
}
expect {
	timeout {puts "TESTING ERROR 0.3\n";exit}
	"UP"
}
expect {
	timeout {puts "TESTING ERROR 0.4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.30.0/24 dev eth1  proto kernel  scope link  src 10.10.30.50" {puts "old iproute2\n";}
	"10.10.30.0/24 dev eth1 proto kernel scope link src 10.10.30.50" {puts "new iproute2\n";}
}

send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"10.10.40.0/24 dev eth2  proto kernel  scope link  src 10.10.40.100" {puts "old iproute2\n";}
	"10.10.40.0/24 dev eth2 proto kernel scope link src 10.10.40.100" {puts "new iproute2\n";}
}


# check default gw
send -- "ip route show\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"default via 10.10.20.2 dev eth0"
}

# check mtu
send -- "ip link show\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"mtu 1000"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"state UP"
}

send -- "exit\r"
after 100

puts "\nall done\n"
