#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=eth0 --net=eth0 --net=eth0 --net=eth0\r"
expect {
	timeout {puts "TESTING ERROR 0.1\n";exit}
	"eth0-"
}
expect {
	timeout {puts "TESTING ERROR 0.2\n";exit}
	"eth1-"
}
expect {
	timeout {puts "TESTING ERROR 0.3\n";exit}
	"eth2-"
}
expect {
	timeout {puts "TESTING ERROR 0.4\n";exit}
	"eth3-"
}
expect {
	timeout {puts "TESTING ERROR 0.5\n";exit}
	"Default gateway 192.168.1.1"
}
expect {
	timeout {puts "TESTING ERROR 0.6\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "exit\r"
sleep 1


after 100

puts "\nall done\n"
