#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --noprofile --debug\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Using the local network stack"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1
send -- "exit\r"
sleep 1

# check loopback
send -- "firejail --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"lo"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"127.0.0.1"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"255.0.0.0"
}
send -- "exit\r"
after 100

puts "all done\n"
