#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# options
send -- "firejail --net=none\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0" {puts "TESTING ERROR 0.1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

# test default gw
send -- "bash\r"
sleep 1
send -- "stty -echo\r"
after 100

send -- "netstat -rn; echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0.0.0.0" {puts "TESTING ERROR 1.1\n";exit}
	"done"
}
sleep 1

# check again devices
send -- "cat /proc/1/net/dev;echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"eth0" {puts "TESTING ERROR 2.1\n";exit}
	"done"
}
send -- "exit\r"
sleep 1
send -- "exit\r"
sleep 1

# profile
send -- "firejail --profile=net_none.profile\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"eth0" {puts "TESTING ERROR 3.1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

# test default gw
send -- "bash\r"
sleep 1
send -- "netstat -rn; echo done\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"0.0.0.0" {puts "TESTING ERROR 4.1\n";exit}
	"done"
}
sleep 1

# check again devices
send -- "cat /proc/1/net/dev;echo done\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"eth0" {puts "TESTING ERROR 5.1\n";exit}
	"done"
}
send -- "exit\r"
after 100

puts "\nall done\n"
