#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# check ip address
send -- "firejail --net=br0 --mtu=1000 --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ip link show\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"mtu 1000"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"state UP"
}
send -- "exit\r"
after 100

puts "\nall done\n"
