#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

#
send -- "firejail --net=br0 --ip=10.10.20.50\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"10.10.20.50"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --net=br0 --ip=10.10.20.60\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"10.10.20.60"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"255.255.255.0"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --net=br0 --scan\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"10.10.20.50"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"10.10.20.60"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

puts "\nall done\n"
