#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --netns=red --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100

send -- "ip link show\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"LOOPBACK"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"DOWN"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"link/loopback"
}
after 100
send -- "exit\r"
after 100

puts "all done\n"
