#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --net=br0\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 4

spawn $env(SHELL)
send -- "firejail --netstats\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"statistics only for sandboxes using a new network namespace"
}
sleep 4

expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"firejail --name=test --net=br0"
}
after 500
puts "\nall done\n"
