#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --net=eth0 --name=test1\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --net=eth0 --name=test2\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --netstats\r"
sleep 4
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"name=test1"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"name=test2"
}
after 100

puts "\n"
