#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --memory-deny-write-execute ./memwrexe mmap\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"mmap successful" {puts "TESTING ERROR 2\n";exit}
	"Parent is shutting down"
}
after 500

send --  "firejail --memory-deny-write-execute ./memwrexe mprotect\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"mprotect successful" {puts "TESTING ERROR 12\n";exit}
	"Parent is shutting down"
}
after 500

send --  "firejail --memory-deny-write-execute ./memwrexe memfd_create\r"
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	"memfd_create successful" {puts "TESTING ERROR 22\n";exit}
	"Parent is shutting down"
}

after 500
puts "\nall done\n"
