# various programs
blacklist ${HOME}/.remmina
blacklist ${HOME}/.tconn
blacklist ${HOME}/.FBReader
blacklist ${HOME}/.wine
blacklist ${HOME}/.Mathematica
blacklist ${HOME}/.Wolfram Research
blacklist ${HOME}/.stellarium
blacklist ${HOME}/.config/mupen64plus
blacklist ${HOME}/.config/transmission
blacklist ${HOME}/.config/uGet
blacklist ${HOME}/.config/Gpredict
blacklist ${HOME}/.config/aweather
blacklist ${HOME}/.config/stellarium
blacklist ${HOME}/.config/atril
blacklist ${HOME}/.config/xreader
blacklist ${HOME}/.config/xviewer
blacklist ${HOME}/.kde/share/apps/okular
blacklist ${HOME}/.kde/share/config/okularrc
blacklist ${HOME}/.kde/share/config/okularpartrc
blacklist ${HOME}/.kde/share/apps/gwenview
blacklist ${HOME}/.kde/share/config/gwenviewrc

# Media players
blacklist ${HOME}/.config/cmus
blacklist ${HOME}/.config/deadbeef
blacklist ${HOME}/.config/spotify
blacklist ${HOME}/.config/vlc
blacklist ${HOME}/.config/totem
blacklist ${HOME}/.config/xplayer

# HTTP / FTP / Mail
blacklist ${HOME}/.icedove
blacklist ${HOME}/.thunderbird
blacklist ${HOME}/.sylpheed-2.0
blacklist ${HOME}/.config/midori
blacklist ${HOME}/.mozilla
blacklist ${HOME}/.config/chromium
blacklist ${HOME}/.config/google-chrome
blacklist ${HOME}/.config/google-chrome-beta
blacklist ${HOME}/.config/google-chrome-unstable
blacklist ${HOME}/.config/opera
blacklist ${HOME}/.config/opera-beta
blacklist ${HOME}/.opera
blacklist ${HOME}/.config/vivaldi
blacklist ${HOME}/.filezilla
blacklist ${HOME}/.config/filezilla
blacklist ${HOME}/.dillo
blacklist ${HOME}/.conkeror.mozdev.org
blacklist ${HOME}/.config/epiphany
blacklist ${HOME}/.config/slimjet
blacklist ${HOME}/.config/qutebrowser
blacklist ${HOME}/.8pecxstudios
blacklist ${HOME}/.config/brave

# Instant Messaging
blacklist ${HOME}/.config/hexchat
blacklist ${HOME}/.mcabber
blacklist ${HOME}/.mcabberrc
blacklist ${HOME}/.purple
blacklist ${HOME}/.config/psi+
blacklist ${HOME}/.retroshare
blacklist ${HOME}/.weechat
blacklist ${HOME}/.config/xchat
blacklist ${HOME}/.Skype
blacklist ${HOME}/.config/tox
blacklist ${HOME}/.TelegramDesktop

# Games
blacklist ${HOME}/.hedgewars
blacklist ${HOME}/.steam
blacklist ${HOME}/.config/wesnoth
blacklist ${HOME}/.config/0ad
blacklist ${HOME}/.warzone2100-3.1

# Cryptocoins
blacklist ${HOME}/.*coin
blacklist ${HOME}/.electrum*
blacklist ${HOME}/wallet.dat

# git, subversion
blacklist ${HOME}/.subversion
blacklist ${HOME}/.gitconfig
blacklist ${HOME}/.git-credential-cache

# cache
blacklist ${HOME}/.cache/mozilla
blacklist ${HOME}/.cache/chromium
blacklist ${HOME}/.cache/google-chrome
blacklist ${HOME}/.cache/google-chrome-beta
blacklist ${HOME}/.cache/google-chrome-unstable
blacklist ${HOME}/.cache/opera
blacklist ${HOME}/.cache/opera-beta
blacklist ${HOME}/.cache/vivaldi
blacklist ${HOME}/.cache/epiphany
blacklist ${HOME}/.cache/slimjet
blacklist ${HOME}/.cache/qutebrowser
blacklist ${HOME}/.cache/spotify
blacklist ${HOME}/.cache/thunderbird
blacklist ${HOME}/.cache/icedove
blacklist ${HOME}/.cache/transmission
blacklist ${HOME}/.cache/wesnoth
blacklist ${HOME}/.cache/0ad
blacklist ${HOME}/.cache/8pecxstudios
blacklist ${HOME}/.cache/xreader

# share
blacklist ${HOME}/.local/share/epiphany
blacklist ${HOME}/.local/share/mupen64plus
blacklist ${HOME}/.local/share/spotify
blacklist ${HOME}/.local/share/steam
blacklist ${HOME}/.local/share/wesnoth
blacklist ${HOME}/.local/share/0ad
blacklist ${HOME}/.local/share/xplayer
blacklist ${HOME}/.local/share/totem
blacklist ${HOME}/.local/share/psi+
