# development tools

# GCC
blacklist /usr/include
blacklist /usr/bin/gcc*
blacklist /usr/bin/cpp*
blacklist /usr/bin/c9*
blacklist /usr/bin/c8*
blacklist /usr/bin/c++*
blacklist /usr/bin/ld

# Valgrind
blacklist /usr/bin/valgrind*
blacklist /usr/lib/valgrind

# Perl
blacklist /usr/bin/perl
blacklist /usr/bin/cpan*
blacklist /usr/share/perl*
blacklist /usr/lib/perl*

# PHP
blacklist /usr/bin/php*
blacklist /usr/share/php*
blacklist /usr/lib/php*

# Ruby
blacklist /usr/bin/ruby
blacklist /usr/lib/ruby
