# Local customizations come here
include whitelist-usr-share-common.local

# common /usr/share whitelist for all profiles

whitelist /usr/share/applications
whitelist /usr/share/cursors
whitelist /usr/share/drirc.d
whitelist /usr/share/fontconfig
whitelist /usr/share/fonts
whitelist /usr/share/glib-2.0
whitelist /usr/share/glvnd
whitelist /usr/share/gtk-3.0
whitelist /usr/share/hwdata
whitelist /usr/share/icons
whitelist /usr/share/Kvantum
whitelist /usr/share/locale
whitelist /usr/share/mime
whitelist /usr/share/Modules
whitelist /usr/share/p11-kit
whitelist /usr/share/pixmaps
whitelist /usr/share/pki
whitelist /usr/share/qt5
whitelist /usr/share/tcl8.6
whitelist /usr/share/terminfo
whitelist /usr/share/themes
whitelist /usr/share/X11
