# Local customizations come here
include whitelist-usr-share-common.local

# common /usr/share whitelist for all profiles

whitelist /usr/share/applications
whitelist /usr/share/cursors
whitelist /usr/share/mime
whitelist /usr/share/fontconfig
whitelist /usr/share/fonts
whitelist /usr/share/glib-2.0
whitelist /usr/share/gtk-3.0
whitelist /usr/share/icons
whitelist /usr/share/themes
whitelist /usr/share/locale
whitelist /usr/share/pixmaps
whitelist /usr/share/X11
