#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --noprofile --caps --debug\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Drop CAP_SYS_MODULE"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Drop CAP_SYS_RAWIO"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Drop CAP_SYS_BOOT"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Drop CAP_SYS_NICE"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Drop CAP_SYS_TTY_CONFIG"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Drop CAP_SYSLOG"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Drop CAP_MKNOD"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Drop CAP_SYS_ADMIN"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --caps.print=test\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"chown               - enabled"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"setgid              - enabled"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"setuid              - enabled"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"mknod               - disabled"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"syslog              - disabled"
}
after 500

send -- "firejail --debug-caps\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"21	- sys_admin"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"22	- sys_boot"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"23	- sys_nice"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"24	- sys_resource"
}
after 500

send -- "firejail --caps.keep=\"bla bla bla\"\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"capability"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"not found"
}

after 500
puts "\nall done\n"
