#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --nettrace\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "only available to root user"
}
after 100

send -- "/usr/lib/firejail/fnettrace\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "you need to be root"
}

send -- "/usr/lib/firejail/fnettrace-dns\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "you need to be root"
}
after 100

send -- "/usr/lib/firejail/fnettrace-sni\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "you need to be root"
}
after 100

send -- "/usr/lib/firejail/fnettrace-icmp\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "you need to be root"
}

after 100
puts "\nexpect script done\r"
