#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private-etc=passwd,group,resolv.conf,X11\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "LC_ALL=C ls -al /etc\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"X11"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"group"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"passwd"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"resolv.conf"
}


send -- "file /etc/shadow\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"No such file or directory"
}
after 100
send -- "exit\r"
sleep 1

send -- "firejail --private-etc=shadow\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"invalid file type"
}
after 100

send -- "firejail --private-etc=\"bla;bla\"\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"is an invalid filename"
}
after 100

send -- "firejail --private-etc=../bin/ls\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"is an invalid filename"
}
after 100

send -- "exit\r"
after 100
puts "\nall done\n"
