#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "rm outfile\r"
after 100

send -- "fnetfilter outfile\r"
after 100

send -- "cat outfile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"*filter"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"INPUT -m state --state RELATED,ESTABLISHED"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"disable STUN"
}
after 100

send -- "fnetfilter test1.net,33\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error:"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"is an invalid filename"
}
after 100

send -- "rm outfile\r"
after 100

puts "\nall done\n"
