#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if {![file exists /usr/bin/chromium]} {
    puts "TESTING: CHROMIUM not installed, skipping...\n"
    after 100
    exit
}



send -- "firejail --private --ignore=quiet chromium\r"
expect {
    timeout {puts "TESTING ERROR 0\n";exit}
    "Reading profile /etc/firejail/chromium.profile"
}
expect {
    timeout {puts "TESTING ERROR 1\n";exit}
    -re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 5

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
    timeout {puts "TESTING ERROR 2\n";exit}
    "firejail"
}
expect {
    timeout {puts "TESTING ERROR 3\n";exit}
    "chromium"
}
after 100

puts "\n"
