#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

set program dig

if {![file exists /usr/bin/$program]} {
	puts "TESTING: $program not installed, skipping...\n"
	after 100
	exit
}

send -- "firejail --ignore=quiet $program cloudflare.com\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/$program.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "ANSWER SECTION"
}
after 100
puts "\nall done\n"
