#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if {![file exists /usr/bin/ffmpeg]} {
    puts "TESTING: ffmpeg not installed, skipping...\n"
    after 100
    exit
}



send -- "firejail --private --ignore=quiet ffmpeg --help\r"
expect {
    timeout {puts "TESTING ERROR 0\n";exit}
    "Reading profile /etc/firejail/ffmpeg.profile"
}
expect {
    timeout {puts "TESTING ERROR 1\n";exit}
    -re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
    timeout {puts "TESTING ERROR 2\n";exit}
    "version"
}

after 100
puts "all done\n"
