#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --ignore=dns --net=enp5s0 firefox --no-remote www.debian.org\r"
expect {
    timeout {puts "TESTING ERROR 0\n";exit}
    "Reading profile /etc/firejail/firefox.profile"
}
expect {
    timeout {puts "TESTING ERROR 0.1\n";exit}
    "Interface"
}
expect {
    timeout {puts "TESTING ERROR 0.2\n";exit}
    "eth0-"
}
expect {
    timeout {puts "TESTING ERROR 0.3\n";exit}
    "Default gateway"
}
expect {
    timeout {puts "TESTING ERROR 1\n";exit}
    -re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 5

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
    timeout {puts "TESTING ERROR 2\n";exit}
    "firejail"
}
expect {
    timeout {puts "TESTING ERROR 3\n";exit}
    "firefox"
}
after 100

spawn $env(SHELL)
send -- "firemon --seccomp\r"
expect {
    timeout {puts "TESTING ERROR 4\n";exit}
    "firefox"
}
expect {
    timeout {puts "TESTING ERROR 5\n";exit}
    "Seccomp:	2"
}
sleep 1

puts "\nall done\n"
