#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --timeout=00:00:03 --private gnome-screenshot --interactive\r"
expect {
    timeout {puts "TESTING ERROR 0\n";exit}
    "Reading profile /etc/firejail/gnome-screenshot.profile"
}
expect {
    timeout {puts "TESTING ERROR 1\n";exit}
    -re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
    timeout {puts "TESTING ERROR 2\n";exit}
    "firejail"
}
expect {
    timeout {puts "TESTING ERROR 3\n";exit}
    "gnome-screenshot"
}
after 100

spawn $env(SHELL)
send -- "firemon --seccomp\r"
expect {
    timeout {puts "TESTING ERROR 4\n";exit}
    "gnome-screenshot"
}
expect {
    timeout {puts "TESTING ERROR 5\n";exit}
    "Seccomp:	2"
}

sleep 3

puts "\nall done\n"
