#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --ignore=quiet sleep 5\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/default.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
        timeout {puts "TESTING ERROR 2\n";exit}
        "Operation not permitted" {puts "TESTING ERROR 3\n";exit}
	"Parent is shutting down"
}
after 100
puts "\nall done\n"
