#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail wine --help\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile /etc/firejail/wine.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Usage: wine PROGRAM"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"wine --version"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Parent is shutting down, bye..."
}

puts "\nall done\n"
