#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --x11=xephyr xterm\r"
sleep 10

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 3.1\n";exit}
	"xterm"
}
sleep 1

# grsecurity exit
send -- "file /proc/sys/kernel/grsecurity\r"
expect {
	timeout {puts "TESTING ERROR - grsecurity detection\n";exit}
	"grsecurity: directory" {puts "grsecurity present, exiting...\n";exit}
	"cannot open" {puts "grsecurity not present\n"}
}

send -- "firejail --name=blablabla\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send -- "firemon --seccomp\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"need to be root" {puts "/proc mounted as hidepid, exiting...\n"; exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 5.0\n";exit}
	"xterm"
}
expect {
	timeout {puts "TESTING ERROR 5.1 (seccomp)\n";exit}
	"Seccomp:	2"
}
expect {
	timeout {puts "TESTING ERROR 5.1\n";exit}
	"name=blablabla"
}
sleep 1
send -- "firemon --caps\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 6.0\n";exit}
	"xterm"
}
expect {
	timeout {puts "TESTING ERROR 6.1\n";exit}
	"CapBnd"
}
expect {
	timeout {puts "TESTING ERROR 6.2\n";exit}
	"0000000000000000"
}
expect {
	timeout {puts "TESTING ERROR 6.3\n";exit}
	"name=blablabla"
}
sleep 1
send -- "firejail --shutdown=test\r"
sleep 3

puts "\nall done\n"
