#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "fcopy\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"arguments missing"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Usage:"
}
after 100

send -- "fcopy foo\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"arguments missing"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Usage:"
}
after 100

send -- "fcopy f%oo1 foo2\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"invalid source file name"
}
after 100

send -- "fcopy foo1 f,oo2\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"invalid dest file name"
}
after 100

puts "\nall done\n"
