#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "/usr/lib/firejail/fcopy\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"files missing"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Usage:"
}
after 100

send -- "/usr/lib/firejail/fcopy foo\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"files missing"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Usage:"
}
after 100

send -- "/usr/lib/firejail/fcopy f%oo1 foo2\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"invalid file name"
}
after 100

send -- "/usr/lib/firejail/fcopy foo1 f,oo2\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"invalid file name"
}
after 100

puts "\nall done\n"
