#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

#
# copy directory src to dest
#
set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "rm -fr dest/*\r"
after 100
send -- "cd src\r"
after 100
send -- "ln -s ../dircopy.exp dircopy.exp\r"
after 100
send -- "cd ..\r"
after 100

send -- "fcopy src dest\r"
after 100
send -- "cd src\r"
after 100
send -- "ln -s ../dircopy.exp dircopy.exp\r"
after 100
send -- "cd ..\r"
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"dest/"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"dest/"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"dest/a"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"dest/a/b"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"dest/a/b/file4"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"dest/a/file3"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"dest/dircopy.exp"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"dest/file2"
}
after 100

send -- "find dest\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"dest/file1"
}
after 100


send -- "ls -al dest\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"drwxr-xr-x" { puts "umask 0022\n" }
	"drwxrwxr-x" { puts "umask 0002\n" }
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"a"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"lrwxrwxrwx"
}
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"dircopy.exp"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"rwxr-xr-x" { puts "umask 0022\n" }
	"rwxrwxr-x" { puts "umask 0002\n" }
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"file1"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"rw-r--r--" { puts "umask 0022\n" }
	"rw-rw-r--" { puts "umask 0002\n" }
}
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	"file2"
}
after 100

send -- "stty -echo\r"
after 100
send -- "diff -q src/a/b/file4 dest/a/b/file4; echo done\r"
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"differ" {puts "TESTING ERROR 17\n";exit}
	"done"
}

send -- "file dest/dircopy.exp\r"
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	"symbolic link"
}

send -- "rm -fr dest/*\r"
after 100
send -- "rm -f src/dircopy.exp\r"
after 100

puts "\nall done\n"
