#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2018 Firejail Authors
# License GPL v2

#
# copy directory src to dest
#
set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private-etc=group,passwd,firejail/ ls /etc/firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"0ad.profile"
}
after 100


puts "\nall done\n"
