#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --caps.keep=chown,fowner --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 2

send -- "cat /proc/self/status\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"CapBnd:	0000000000000009"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Seccomp:"
}
send -- "exit\r"
sleep 1

send -- "firejail --caps.drop=all --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 2

send -- "cat /proc/self/status\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"CapBnd:	0000000000000000"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Seccomp:"
}
send -- "exit\r"
sleep 1

send -- "firejail --caps.drop=chown,dac_override,dac_read_search,fowner --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Child process initialized"
}
sleep 2

send -- "cat /proc/self/status\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"CapBnd:"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"fffffff0"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Seccomp:"
}
send -- "exit\r"
after 100


puts "\nall done\n"
