#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --noprofile --protocol=unix --debug\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0009: 20 00 00 00000000   ld  data.syscall-number"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"000a: 15 01 00 00000029   jeq socket 000c (false 000b)"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"000b: 06 00 00 7fff0000   ret ALLOW"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"000c: 20 00 00 00000010   ld  data.args"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"000d: 15 00 01 00000001   jeq 1 000e (false 000f)"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"000e: 06 00 00 7fff0000   ret ALLOW"
	""
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"000f: 06 00 00 0005005f   ret ERRNO(95)"
}

after 100
send -- "exit\r"
after 100
puts "\nall done\n"
