#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 1
spawn $env(SHELL)
match_max 100000

send -- "./syscall_test\r"
expect {
        timeout {puts "\nTESTING SKIP: 64-bit support missing\n";exit}
	"Usage"
}

send -- "./syscall_test32\r"
expect {
        timeout {puts "\nTESTING SKIP: 32-bit support missing\n";exit}
        "Usage"
}

set timeout 10
send -- "firejail ./syscall_test mount\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"before mount"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"after mount" {puts "TESTING ERROR 3\n";exit}
	"Parent is shutting down"
}
sleep 1

send -- "firejail ./syscall_test32 mount\r"
expect {
        timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"before mount"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"after mount" {puts "TESTING ERROR 7\n";exit}
	"Parent is shutting down"
}

after 100
puts "\nall done\n"
