#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "stty -echo\r"
after 100

send --  "firejail --debug sleep 1; echo done\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"seccomp entries in /run/firejail/mnt/seccomp/seccomp"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"jeq open_by_handle_at"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"done"
}
after 100


# 64 bit architecture
send --  "firejail --debug sleep 1; echo done\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"done"
}
after 100

# 64 bit architecture - ignore seccomp
send --  "firejail --debug --ignore=seccomp sleep 1; echo done\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp seccomp filter" {puts "TESTING ERROR 11\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter" {puts "TESTING ERROR 12\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp seccomp filter" {puts "TESTING ERROR 14\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter" {puts "TESTING ERROR 15\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"done"
}
after 100

# 64 bit architecture - ignore protocol
send --  "firejail --debug --ignore=protocol sleep 1; echo done\r"
expect {
	timeout {puts "TESTING ERROR 17\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter" {puts "TESTING ERROR 18\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 19\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter" {puts "TESTING ERROR 20\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.protocol seccomp filter" {puts "TESTING ERROR 22\n";exit}
	"Installing /run/firejail/mnt/seccomp/seccomp.32 seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	"done"
}
after 100

puts "all done\n"
