#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --profile=seccomp.profile --private\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "stty -echo\r"
after 100
send -- "cd ~; echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"done"
}

send -- "touch testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}

send -- "ls -l testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"testfile"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"done"
}

send -- "chmod +x testfile; echo done\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Operation not permitted"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"done"
}

send -- "exit\r"
after 100
puts "\nall done\n"
