#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp --debug\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"SECCOMP Filter"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"BLACKLIST"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"open_by_handle_at"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 2

send -- "exit\r"
after 100
puts "all done\n"
