#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp=chown,fchown,fchownat,lchown --private\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

send -- "touch testfile;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/root" {puts "running as root"}
	"/home"
}

send -- "ls -l testfile;pwd\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"testfile"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"/root" {puts "running as root"}
	"/home"
}

send -- "chown netblue:netblue testfile;pwd\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Bad system call"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"/root" {puts "running as root"}
	"/home"
}


send -- "exit\r"
after 100
puts "\nall done\n"
