#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --noprofile --seccomp\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

send -- "sudo su -\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"effective uid is not 0"
}

send -- "sudo ls\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"effective uid is not 0"
}

send -- "ping google.com\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Operation not permitted"
}

send -- "exit\r"
sleep 1
puts "all done\n"
