#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10

# disable strace's terminal background color probing
set env(NO_COLOR) 1

spawn $env(SHELL)
match_max 100000

send --  "firejail --noprofile --seccomp\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

send -- "strace ls\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"not permitted"
}

send -- "exit\r"
after 100
puts "all done\n"
