#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail ./syscall_test mount\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"before mount"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"after mount" {puts "TESTING ERROR 2.1\n";exit}
	"Parent is shutting down"
}
sleep 1

send -- "firejail ./syscall_test32 mount\r"
expect {
        timeout {puts "TESTING ERROR 4\n";exit}
	"No such file or directory" {puts "\nTESTING SKIP 3: can't execute 32 bit binary\n"; exit}
	"Parent is shutting down, bye" {puts "\nTESTING SKIP 3: can't execute 32 bit binary\n"; exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"before mount"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"after mount" {puts "TESTING ERROR 6.1\n";exit}
	"Parent is shutting down"
}

puts "\nall done\n"
