#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --seccomp=\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --seccomp.drop=\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --seccomp.keep=\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error: empty syscall lists are not allowed"
}

send --  "firejail --profile=seccomp-bad-empty.profile\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Error: line 1 in seccomp-bad-empty.profile is invalid"
}

send --  "firejail --profile=seccomp-bad-empty2.profile\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Error: line 1 in seccomp-bad-empty2.profile is invalid"
}
after 100
puts "\nall done\n"
