#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --debug --seccomp=execve\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"configuring postexec seccomp filter in"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"data.architecture"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"monitoring pid"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Sandbox monitor: waitpid"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Parent is shutting down"
}
sleep 1

puts "all done\n"
