#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --noprofile --seccomp\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

send -- "strace ls\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"not permitted"
}

send -- "exit\r"
after 100
puts "all done\n"
