#!/usr/bin/expect -f

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --profile=/etc/firejail/firefox.profile --allow-debuggers strace ls\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
        timeout {puts "TESTING ERROR 1\n";exit}
        "ioctl"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"exit_group"
}
after 100

send -- "firejail --allow-debuggers --profile=/etc/firejail/firefox.profile strace ls\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
expect {
        timeout {puts "TESTING ERROR 4\n";exit}
        "ioctl"
}       
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"exit_group"
}
after 100


puts "\nall done\n"

