#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --allow-debuggers\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" { puts "\n"}
	"is disabled on Linux kernels prior to 4.8" { puts "TESTING SKIP: kernel too old\n"; exit }
}
after 100

send -- "strace ls\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"open"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"exit_group"
}
after 100
send -- "exit\r"
sleep 1



puts "\nall done\n"
