#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --tracelog --csh\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "find /home\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	".cshrc"
}

send -- "env | grep SHELL\r"
expect {
        timeout {puts "TESTING ERROR 2\n";exit}
        "SHELL"
}
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"/bin/csh"
}
send -- "exit\r"
after 100

puts "\n"

