#!/usr/bin/expect -f

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --shell=/bin/csh\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "env | grep SHELL;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"SHELL"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"/bin/csh"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"home"
}
send -- "exit\r"
after 100

puts "\nall done\n"
