#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --tracelog --shell=/bin/dash\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

#send -- "ls -al;pwd\r"
#expect {
#	timeout {puts "TESTING ERROR 1\n";exit}
#	".zshrc"
#}
#expect {
#	timeout {puts "TESTING ERROR 1.1\n";exit}
#	"home"
#}

send -- "env | grep SHELL;pwd\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"SHELL"
}
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"/bin/dash"
}
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"home"
}
send -- "exit\r"
after 100

puts "\n"
