#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 4
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "({ nohup bash -c \"sleep 0.2; exit 53\" &> /dev/null & } &)\r"
send -- "exit 35\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Parent is shutting down"
}
after 300

send -- "echo $?\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"53"
}
after 100

send -- "firejail --deterministic-exit-code\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "({ nohup bash -c \"sleep 0.2; exit 53\" &> /dev/null & } &)\r"
send -- "exit 35\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Parent is shutting down"
}
after 300

send -- "echo $?\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"35"
}
after 100


puts "\nall done\n"
