#!/usr/bin/expect -f

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "firejail --dns=8.8.4.4 --dns=8.8.8.8 --dns=4.2.2.1 --dns=::2\r"
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "cat /etc/resolv.conf\r"
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"nameserver 8.8.4.4"
}
expect {
	timeout {puts "TESTING ERROR 2.3\n";exit}
	"nameserver 8.8.8.8"
}
expect {
	timeout {puts "TESTING ERROR 2.4\n";exit}
	"nameserver 4.2.2.1"
}
expect {
	timeout {puts "TESTING ERROR 2.5\n";exit}
	"nameserver ::2"
}
after 100
send -- "exit\r"
sleep 1


send -- "firejail --profile=dns.profile\r"
expect {
	timeout {puts "TESTING ERROR 12.1\n";exit}
	"Child process initialized"
}
sleep 1

send -- "cat /etc/resolv.conf\r"
expect {
	timeout {puts "TESTING ERROR 12.2\n";exit}
	"nameserver 8.8.4.4"
}
expect {
	timeout {puts "TESTING ERROR 12.3\n";exit}
	"nameserver 8.8.8.8"
}
expect {
	timeout {puts "TESTING ERROR 12.4\n";exit}
	"nameserver 4.2.2.1"
}
after 100
expect {
	timeout {puts "TESTING ERROR 12.5\n";exit}
	"nameserver ::2"
}
send -- "exit\r"
sleep 1

send -- "firejail --trace --dns=208.67.222.222 wget -q debian.org\r"
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"connect"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"208.67.222.222"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"53"
}
after 100

send -- "rm index.html\r"
after 100
send -- "exit\r"
sleep 1

puts "\nall done\n"
