#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

send --  "firejail\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Warning: an existing sandbox was detected"
}
after 100

send --  "exit\r"
after 100

send --  "firejail --force\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"cannot rise privileges"
}
after 100

send --  "firejail --version\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"firejail version"
}
after 100

send --  "firejail --version --force\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"firejail version"
}
after 100


puts "\nall done\n"
