#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

send -- "env | grep IBUS\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"IBUS_ADDRESS"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"IBUS_DAEMON_PID"
}
after 100


puts "\nall done\n"
