#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2


set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug --machine-id\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Generating a new machine-id"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100
send -- "exit\r"
after 100

puts "\nall done\n"
