#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --rlimit-fsize=-1024\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"invalid rlimit"
}
after 100

send -- "firejail --rlimit-nofile=asdf\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"invalid rlimit"
}
after 100

send -- "firejail --rlimit-nproc=100.23\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"invalid rlimit"
}
after 100
send -- "firejail --rlimit-sigpending=2345-78\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"invalid rlimit"
}
after 100

puts "\nall done\n"
