#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --profile=rlimit-bad1.profile\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"invalid rlimit"
}
after 100

send -- "firejail --profile=rlimit-bad2.profile\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"invalid rlimit"
}
after 100

send -- "firejail --profile=rlimit-bad3.profile\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"invalid rlimit"
}
after 100
send -- "firejail --profile=rlimit-bad4.profile\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"invalid rlimit"
}
after 100

puts "\nall done\n"
