#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send --  "firejail --noprofile --name=\"rlimittesting\"\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --rlimit-nofile=1234 --join=\"rlimittesting\"\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Switching to pid"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "cat /proc/self/limits\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Max open files            1234                 1234"
}
after 100

send -- "exit\r"
after 100

puts "\nall done\n"
