#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send -- "firejail --rlimit-fsize=1024 --rlimit-nproc=1000 --rlimit-nofile=500 --rlimit-sigpending=200 --rlimit-as=1234567890\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "cat /proc/self/limits; pwd\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Max file size             1024                 1024"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"Max processes             1000                 1000"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"Max open files            500                  500"
}
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"Max address space         1234567890           1234567890"
}
expect {
	timeout {puts "TESTING ERROR 1.5\n";exit}
	"Max pending signals       200                  200"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"home"
}
after 100
puts "\nall done\n"
