#!/usr/bin/expect -f
#
# disable /selinux
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /selinux\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied" {puts "denied\n"}
	"No such file or directory" {puts "no file\n"}
}
after 100
send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ls -l /selinux\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"Permission denied" {puts "denied\n"}
		"No such file or directory" {puts "no file\n"}
	}
	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ls -l /selinux\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"Permission denied" {puts "denied\n"}
		"No such file or directory" {puts "no file\n"}
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
