#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# disable /etc/firejail and ~/.config/firejail
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
sleep 1
send -- "firejail --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls ~/.config/firejail\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Permission denied"
}
after 100
send -- "ls /run/firejail/bandwidth\r"
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"Permission denied"
}
after 100
#send -- "ls /run/firejail/mnt\r"
#expect {
#	timeout {puts "TESTING ERROR 1.3\n";exit}
#	"Permission denied"
#}
#after 100
send -- "ls /run/firejail/name\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"Permission denied"
}
after 100
send -- "ls /run/firejail/network\r"
expect {
	timeout {puts "TESTING ERROR 1.5\n";exit}
	"Permission denied"
}
after 100
send -- "ls /run/firejail/x11\r"
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"Permission denied"
}
after 100
send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "normal system\n"}
	}
	sleep 1
	send -- "ls ~/.config/firejail\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/bandwidth\r"
	expect {
		timeout {puts "TESTING ERROR 3.2\n";exit}
		"Permission denied"
	}
	after 100
	#send -- "ls /run/firejail/mnt\r"
	#expect {
	#	timeout {puts "TESTING ERROR 3.3\n";exit}
	#	"Permission denied"
	#}
	#after 100
	send -- "ls /run/firejail/name\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/network\r"
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/x11\r"
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"Permission denied"
	}
	after 100

	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1
	send -- "ls ~/.config/firejail\r"
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/bandwidth\r"
	expect {
		timeout {puts "TESTING ERROR 5.2\n";exit}
		"Permission denied"
	}
	after 100
	#send -- "ls /run/firejail/mnt\r"
	#expect {
	#	timeout {puts "TESTING ERROR 5.3\n";exit}
	#	"Permission denied"
	#}
	#after 100
	send -- "ls /run/firejail/name\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/network\r"
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"Permission denied"
	}
	after 100
	send -- "ls /run/firejail/x11\r"
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"Permission denied"
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
