#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2
#
# hostname
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --hostname=bingo\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "hostname\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"bingo"
}
after 100
send -- "cat /etc/hostname\r"
expect {
	timeout {puts "TESTING ERROR 1.0\n";exit}
	"bingo"
}
after 100
send -- "getent hosts bingo\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"127.0.0.1"
}
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"bingo"
}
after 100
send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --hostname=bingo --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		"Child process initialized" {puts "normal system\n"}
	}
	sleep 1

	send -- "hostname\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"bingo"
	}
	after 100
	send -- "cat /etc/hostname\r"
	expect {
		timeout {puts "TESTING ERROR 3.0\n";exit}
		"bingo"
	}
	after 100
	send -- "getent hosts bingo\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"127.0.0.1"
	}
	expect {
		timeout {puts "TESTING ERROR 3.2\n";exit}
		"bingo"
	}
	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --hostname=bingo --chroot=/tmp/chroot\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "hostname\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"bingo"
	}
	after 100
	send -- "cat /etc/hostname\r"
	expect {
		timeout {puts "TESTING ERROR 5.0\n";exit}
		"bingo"
	}
	after 100
	send -- "getent hosts bingo\r"
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"127.0.0.1"
	}
	expect {
		timeout {puts "TESTING ERROR 5.2\n";exit}
		"bingo"
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
