#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# mac-vlan
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --net=eth0 --dns=8.8.8.8 --dns=8.8.4.4\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "dig google.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"ANSWER SECTION"
}
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"google.com"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"SERVER:"
}
after 100

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"192.168.1"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 3

send -- "firejail --noprofile --net=eth0 --ip=192.168.1.244 --dns=8.8.8.8 --dns=8.8.4.4\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "dig google.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"ANSWER SECTION"
}
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"google.com"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"SERVER:"
}
after 100

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"192.168.1.244"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 3

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile  --net=eth0 --overlay --dns=8.8.8.8 --dns=8.8.4.4\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		"Child process initialized" {puts "normal system\n"}
	}
	sleep 1

	send -- "dig google.com\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"ANSWER SECTION"
	}
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"google.com"
	}
	expect {
		timeout {puts "TESTING ERROR 3.3\n";exit}
		"SERVER"
	}
	after 100

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"192.168.1"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 3

	send -- "firejail --noprofile  --net=eth0 --ip=192.168.1.244 --overlay --dns=8.8.8.8 --dns=8.8.4.4\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "dig google.com\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"ANSWER SECTION"
	}
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"google.com"
	}
	expect {
		timeout {puts "TESTING ERROR 3.3\n";exit}
		"SERVER"
	}
	after 100

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"192.168.1.244"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 3
}


#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --net=eth0 --chroot=/tmp/chroot --dns=8.8.8.8 --dns=8.8.4.4\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "dig google.com\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"ANSWER SECTION"
	}
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"google.com"
	}
	expect {
		timeout {puts "TESTING ERROR 5.3\n";exit}
		"SERVER:"
	}
	after 100

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"192.168.1"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 3

	send -- "firejail --noprofile --net=eth0 --ip=192.168.1.244 --chroot=/tmp/chroot --dns=8.8.8.8 --dns=8.8.4.4\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "dig google.com\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"ANSWER SECTION"
	}
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"google.com"
	}
	expect {
		timeout {puts "TESTING ERROR 5.3\n";exit}
		"SERVER:"
	}
	after 100

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"192.168.1.244"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
