#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# bridge
# - todo: ping test or equivalent on chroot
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --net=br0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ping -c 3 10.10.20.1\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	" packets transmitted, 3 received, 0% packet loss"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"10.10.20"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1

send -- "firejail --noprofile --net=br0 --ip=10.10.20.4\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ping -c 3 10.10.20.1\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	" packets transmitted, 3 received, 0% packet loss"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"10.10.20.4"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile  --net=br0 --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "normal system\n"}
	}
	sleep 1

	send -- "ping -c 3 10.10.20.1\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		" packets transmitted, 3 received, 0% packet loss"
	}
	sleep 1


	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"10.10.20"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 1

	send -- "firejail --noprofile  --net=br0 --ip=10.10.20.4 --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "ping -c 3 10.10.20.1\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		" packets transmitted, 3 received, 0% packet loss"
	}
	sleep 1


	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"10.10.20.4"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 1
}


#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --net=br0 --chroot=/tmp/chroot\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"10.10.20"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 1

	send -- "firejail --noprofile --net=br0 --ip=10.10.20.4 --chroot=/tmp/chroot\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"10.10.20.4"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100

	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
