#!/usr/bin/expect -f
#
# bridge
# - todo: ping test or equivalent on chroot
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]

#
# N
#
send -- "firejail --noprofile --net=br0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ping -c 3 10.10.20.1\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	" packets transmitted, 3 received, 0% packet loss"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"10.10.20"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1

send -- "firejail --noprofile --net=br0 --ip=10.10.20.4\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ping -c 3 10.10.20.1\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	" packets transmitted, 3 received, 0% packet loss"
}
sleep 1


send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"10.10.20.4"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile  --net=br0 --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ping -c 3 10.10.20.1\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		" packets transmitted, 3 received, 0% packet loss"
	}
	sleep 1
	
	
	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"10.10.20"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100
	
	send -- "exit\r"
	sleep 1
	
	send -- "firejail --noprofile  --net=br0 --ip=10.10.20.4 --overlay\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ping -c 3 10.10.20.1\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		" packets transmitted, 3 received, 0% packet loss"
	}
	sleep 1
	
	
	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"10.10.20.4"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100
	
	send -- "exit\r"
	sleep 1
}


#
# C
#
send -- "firejail --noprofile --net=br0 --chroot=/tmp/chroot\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 1

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 5.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 5.5\n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 5.6\n";exit}
	"10.10.20"
}
expect {
	timeout {puts "TESTING ERROR 5.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1

send -- "firejail --noprofile --net=br0 --ip=10.10.20.4 --chroot=/tmp/chroot\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
sleep 1

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 5.4\n";exit}
	"eth0"
}
expect {
	timeout {puts "TESTING ERROR 5.5\n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 5.6\n";exit}
	"10.10.20.4"
}
expect {
	timeout {puts "TESTING ERROR 5.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100

send -- "exit\r"
sleep 1




puts "\nall done\n"
