#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# interface
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --interface=eth0.5\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "/sbin/ifconfig\r"
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"eth0.5"
}
expect {
	timeout {puts "TESTING ERROR 1.5n";exit}
	"Link"
}
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"10.10.205.10"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
}
after 100
send -- "exit\r"
sleep 1

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --interface=eth0.6\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		"Child process initialized" {puts "normal system\n"}
	}
	sleep 1

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"eth0.6"
	}
	expect {
		timeout {puts "TESTING ERROR 3.5n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"10.10.206.10"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot --interface=eth0.7\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "/sbin/ifconfig\r"
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"eth0.7"
	}
	expect {
		timeout {puts "TESTING ERROR 5.5n";exit}
		"Link"
	}
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"10.10.207.10"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1"
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
