#!/usr/bin/expect -f
#
# tmpfs
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]

#
# N
#
send -- "touch ~/.config/firejail-test-file\r"
sleep 1
send -- "firejail --noprofile --tmpfs=/home/netblue/.config\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls ~/.config | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0"
}
after 100
send -- "exit\r"
sleep 1

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --tmpfs=/home/netblue/.config\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ls ~/.config | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"0"
	}
	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "touch /tmp/chroot/home/netblue/.config/firejail-test-file\r"
	sleep 1
	send -- "firejail --noprofile --chroot=/tmp/chroot --tmpfs=/home/netblue/.config\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1
	
	send -- "ls ~/.config | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"0"
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
