#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# whitelist tmp
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "mkdir /tmp/test1dir\r"
sleep 1
send -- "touch /tmp/test1dir/test1\r"
sleep 1
send -- "firejail --noprofile --whitelist=/tmp/test1dir\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /tmp | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"2"
}
send -- "ls -l /tmp\r"
expect {
	timeout {puts "TESTING ERROR 1.2\n";exit}
	"netblue"
}
expect {
	timeout {puts "TESTING ERROR 1.3\n";exit}
	"netblue"
}
expect {
	timeout {puts "TESTING ERROR 1.4\n";exit}
	"test1dir"
}

send -- "ls -l /tmp/test1dir | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1.5\n";exit}
	"2"
}
send -- "ls -l /tmp/test1dir\r"
expect {
	timeout {puts "TESTING ERROR 1.6\n";exit}
	"netblue"
}
expect {
	timeout {puts "TESTING ERROR 1.7\n";exit}
	"netblue"
}
expect {
	timeout {puts "TESTING ERROR 1.8\n";exit}
	"test1"
}


after 100
send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay  --whitelist=/tmp/test1dir\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		"Child process initialized" {puts "normal system\n"}
	}
	sleep 1

	send -- "ls -l /tmp | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"2"
	}
	send -- "ls -l /tmp\r"
	expect {
		timeout {puts "TESTING ERROR 3.2\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 3.3\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 3.4\n";exit}
		"test1dir"
	}

	send -- "ls -l /tmp/test1dir | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3.5\n";exit}
		"2"
	}
	send -- "ls -l /tmp/test1dir\r"
	expect {
		timeout {puts "TESTING ERROR 3.6\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 3.7\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 3.8\n";exit}
		"test1"
	}

	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "mkdir /tmp/chroot/tmp/test1dir\r"
	sleep 1
	send -- "touch /tmp/chroot/tmp/test1dir/test1\r"
	sleep 1
	send -- "firejail --noprofile --chroot=/tmp/chroot  --whitelist=/tmp/test1dir\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "ls -l /tmp | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"2"
	}
	send -- "ls -l /tmp\r"
	expect {
		timeout {puts "TESTING ERROR 5.2\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 5.3\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 5.4\n";exit}
		"test1dir"
	}

	send -- "ls -l /tmp/test1dir | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 5.5\n";exit}
		"2"
	}
	send -- "ls -l /tmp/test1dir\r"
	expect {
		timeout {puts "TESTING ERROR 5.6\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 5.7\n";exit}
		"netblue"
	}
	expect {
		timeout {puts "TESTING ERROR 5.8\n";exit}
		"test1"
	}

	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
