#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2023 Firejail Authors
# License GPL v2
#
# read-only
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "rm -f ~/.config/firejail-test-file\r"
sleep 1
send -- "firejail --noprofile --read-only=/home/netblue/.config\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "touch ~/.config/firejail-test-file\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Read-only file system"
}
after 100
send -- "exit\r"
sleep 1

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --read-only=/home/netblue/.config\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "normal system\n"}
	}
	sleep 1

	send -- "touch ~/.config/firejail-test-file\r"
	expect {
		timeout {puts "TESTING ERROR 3\n";exit}
		"Read-only file system"
	}
	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "rm -f /tmp/chroot/home/netblue/.config/firejail-test-file\r"
	sleep 1
	send -- "firejail --noprofile --chroot=/tmp/chroot --read-only=/home/netblue/.config\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "touch ~/.config/firejail-test-file\r"
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"Read-only file system"
	}
	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
