#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# private-etc
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --private-etc=group,hostname,hosts,nsswitch.conf,passwd,resolv.conf,skel\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -al /etc | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"10"
}

after 100
send -- "exit\r"
sleep 1

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --private-etc=group,hostname,hosts,nsswitch.conf,passwd,resolv.conf,skel\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "normal system\n"}
	}
	sleep 1

	send -- "ls -al /etc | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"10"
	}

	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot --private-etc=group,hostname,hosts,nsswitch.conf,passwd,resolv.conf,skel\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"chroot option is not available" {puts "grsecurity\n"; exit}
		"private-etc feature is disabled in chroot"
	}
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"chroot option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "ls /etc | grep firejail\r"
	expect {
		timeout {puts "TESTING ERROR 6\n";exit}
		"firejail"
	}

	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
