#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# private-bin
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --private-bin=bash,cat,cp,ls,wc\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /usr/bin | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"6"
}


after 100
send -- "exit\r"
sleep 1

#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --private-bin=bash,cat,cp,ls,wc\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		"Child process initialized" {puts "normal system\n"}
	}
	sleep 1

	send -- "ls -l /usr/bin | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"6"
	}


	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot --private-bin=bash,cat,cp,ls,wc\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		"private-bin feature is disabled in chroot"
	}
	expect {
		timeout {puts "TESTING ERROR 5\n";exit}
		"Child process initialized"
	}
	sleep 1

	send -- "ls -l /usr/bin | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 6\n";exit}
		"9"
	}

	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
