#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2
#
# whitelist dev
#

set timeout 10
spawn $env(SHELL)
match_max 100000
set overlay [lindex $argv 0]
set chroot [lindex $argv 1]

#
# N
#
send -- "firejail --noprofile --whitelist=/dev/tty --whitelist=/dev/null\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -l /dev | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"3"
}


after 100
send -- "exit\r"
sleep 1


#
# O
#
if { $overlay == "overlay" } {
	send -- "firejail --noprofile --overlay --whitelist=/dev/tty --whitelist=/dev/null\r"
	expect {
		timeout {puts "TESTING ERROR 2\n";exit}
		"overlay option is not available" {puts "grsecurity\n"; exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "normal system\n"}
	}
	sleep 1

	send -- "ls -l /dev | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 3.1\n";exit}
		"3"
	}


	after 100
	send -- "exit\r"
	sleep 1
}

#
# C
#
if { $chroot == "chroot" } {
	send -- "firejail --noprofile --chroot=/tmp/chroot --whitelist=/dev/tty --whitelist=/dev/null\r"
	expect {
		timeout {puts "TESTING ERROR 4\n";exit}
		-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
	}
	sleep 1

	send -- "ls -l /dev | wc -l\r"
	expect {
		timeout {puts "TESTING ERROR 5.1\n";exit}
		"3"
	}

	after 100
	send -- "exit\r"
	sleep 1
}


puts "\nall done\n"
