#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "ssh firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized" {puts "OK\n"}
	"an existing sandbox was detected" {puts "OK\n"}
}
sleep 1

send -- "ps aux | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"5"
}
after 100

send -- "ls -l /home | grep drw | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"1"
}
after 100

send -- "cat /proc/self/status | grep Seccomp\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"2"
}
after 100

send -- "cat /proc/self/status | grep CapBnd\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"0000000000000000"
}
after 100

# preparing scp/sftp tests
send -- "rm testfile\r"

send -- "exit\r"
sleep 1

puts "\nall done\n"
