#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "ssh firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "OK\n"}
	"an existing sandbox was detected" {puts "OK\n"}
}
sleep 1

send -- "rm -f testfile\r"
after 100
send -- "exit\r"
sleep 1

send -- "echo 12345 > testfile\r"
after 100
send -- "scp testfile firejail-test@0:~/testfile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"100%"
}
sleep 1


send -- "ssh firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "OK\n"}
	"an existing sandbox was detected" {puts "OK\n"}
}
sleep 1
send -- "cat testfile\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"12345"
}
after 100
send -- "exit\r"
sleep 1

send -- "rm testfile\r"
after 100
send -- "scp firejail-test@0:~/testfile testfile\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"100%"
}
sleep 1
send -- "cat testfile\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"12345"
}
after 100
send -- "rm testfile\r"
sleep 1

puts "\nall done\n"
