#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "ssh firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized" {puts "OK\n"}
	"an existing sandbox was detected" {puts "OK\n"}
}
sleep 1

send -- "rm -f testfile\r"
after 100
send -- "exit\r"
sleep 1

send -- "echo 12345 > testfile\r"
after 100
send -- "sftp firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Connected to 0"
}
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"sftp>"
}
after 100
send -- "put testfile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"100%"
}
after 100
send -- "exit\r"
sleep 1


send -- "ssh firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized" {puts "OK\n"}
	"an existing sandbox was detected" {puts "OK\n"}
}
sleep 1
send -- "cat testfile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"12345"
}
after 100
send -- "exit\r"
sleep 1

send -- "rm testfile\r"
after 100
send -- "sftp firejail-test@0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Connected to 0"
}
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"sftp>"
}
after 100
send -- "get testfile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"100%"
}
after 100
send -- "exit\r"
sleep 1
send -- "cat testfile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"12345"
}
after 100
send -- "rm testfile\r"
sleep 1

puts "\nall done\n"
