#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug --nodbus --profile=cond1.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"conditional HAS_NODBUS, private"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "exit\r"
sleep 1

send -- "firejail --debug --profile=cond1.profile\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"conditional HAS_NODBUS, private" {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "exit\r"
sleep 1

send -- "firejail --profile=cond2.profile\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"invalid conditional syntax"
}
after 100

send -- "firejail --profile=cond3.profile\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"invalid conditional syntax"
}
after 100

puts "\nall done\n"
