#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "mkdir /tmp/firejailtestdir\r"
send -- "touch /tmp/firejailtestfile\r"
sleep 1

send -- "firejail --profile=readonly.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

send -- "ls > /tmp/firejailtestdir/ttt\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Read-only file system"
}
sleep 1

send -- "ls > /tmp/firejailtestfile\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Read-only file system"
}
send -- "exit\r"
after 100

send -- "rm -fr /tmp/firejailtest*\r"
after 100

puts "\nall done\n"
