#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --profile=test2.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Reading profile test2.profile"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Reading profile test.profile"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cannot access profile file"
}

after 100
puts "\nall done\n"
