#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --ignore=quiet --profile=wget --profile=curl bwrap\r"
expect {
    timeout {puts "TESTING ERROR 0\n";exit}
    "disable-programs"
}
expect {
    timeout {puts "TESTING ERROR 1\n";exit}
    "disable-programs"
}
expect {
    timeout {puts "TESTING ERROR 2\n";exit}
    "fbwrap - bwrap replacement for Firejail sandbox"
}
after 100
puts "all done\n"
