#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

if { $argc != 1 } {
	puts "TESTING ERROR: argument missing"
	puts "Usage: test-profile.exp profile_name"
	exit
}

send -- "firejail --profile=$argv bwrap\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"fbwrap - bwrap replacement for Firejail sandbox"
}
after 100
puts "\n"
