#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --caps.print=test\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"setgid              - disabled"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"setuid              - disabled"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"net_raw             - disabled"
}
after 100
puts "\nall done\n"
