#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --quiet --private-etc=passwd,group -c ls -al /etc\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"cron" {puts "TESTING ERROR 2\n";exit}
	"group"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"passwd"
}


after 100
puts "\nall done\n"
