#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2017 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --cpu=1,2\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --cpu.print=test\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Cpus_allowed_list:	1-2"
}
after 100
puts "\nall done\n"
