#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test --cpu=0\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1
send -- "cat /proc/self/status | grep Cpus\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Cpus"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"_allowed_list:	0"
}
after 100
send -- "exit\r"
sleep 1


send -- "firejail --name=test --cpu=1\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --cpu.print=test\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Cpus"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"_allowed_list:	1"
}
after 100
puts "\nall done\n"
