#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=test1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firejail --name=test2\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send --  "firemon --cgroup\r"
sleep 4
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"need to be root" {puts "TESTING SKIP: /proc mounted as hidepid\n"; exit}
	"name=test1"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"name=test2"
}

after 100

puts "\nall done\n"
