#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=test\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

spawn $env(SHELL)
send --  "firemon --cpu --name=test\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"need to be root" {puts "TESTING SKIP: /proc mounted as hidepid\n"; exit}
	"Cpus_allowed_list"
}

after 100

puts "\nall done\n"
