#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --help\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"License GPL version 2 or later"
}
after 100

send -- "firejail -?\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"License GPL version 2 or later"
}
after 100

puts "\n"
