#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
cd /home
spawn $env(SHELL)
match_max 100000

send --  "cat /tmp/output\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "seccomp not enabled"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "I can run programs in /home"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "I can read ~/.ssh"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "I can access /usr/bin/sudo"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	-re "Networking: enabled"
}
sleep 1

puts "\nall done\r"

