#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=test123 --profile=join5.profile\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Child process initialized"
}
sleep 1
spawn $env(SHELL)
send --  "firejail --join=test123\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Switching to pid"
}
sleep 1
send -- "ps aux\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"/bin/bash"
}

send -- "exit\r"
after 100

send --  "firejail --protocol.print=test123\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Switching to pid"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"unix"
}

puts "\nall done\n"
