#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=svntesting\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 3

spawn $env(SHELL)
send --  "firejail --join=svntesting;pwd\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Switching to pid"
}
sleep 1


spawn $env(SHELL)
send --  "firejail --shutdown=svntesting;pwd\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"home"
}
sleep 1

send --  "firejail --list;pwd\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"svntesting" {puts "TESTING ERROR 5\n";exit}
	"home"
}
sleep 1

puts "\nall done\n"
