#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send --  "firejail --profile=name.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send --  "firejail --join=jointesting\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Switching to pid"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1
send -- "ps aux\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"/bin/bash"
}

send -- "exit\r"
after 100

puts "\nall done\n"
