#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "rm -f lstesting\r"
sleep 1
send -- "firejail --private --name=test\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 2
send -- "echo my_testing > ~/lstesting\r"
sleep 2


spawn $env(SHELL)
send -- "firejail --ls=test ~/.\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"lstesting"
}
sleep 1
send -- "firejail --get=test ~/lstesting\r"
sleep 2
send -- "cat lstesting\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"my_testing"
}
sleep 1
send -- "rm -f lstesting\r"

after 100
puts "\nall done\n"
