#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "man firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"(press RETURN)" {puts "TESTING SKIP 1.1\n";exit}
	"Press RETURN to continue" {puts "TESTING SKIP 1.2\n";exit}
	"Linux namespaces sandbox program"
}
after 100

send -- "q\r"
after 100
puts "\n"
