#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2018 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	":ftest:"
}
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	":ftest-1:"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	":ftest-2:"
}
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	":ftest-3:"
}
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	":ftest-4:"
}
expect {
	timeout {puts "TESTING ERROR 17\n";exit}
	":ftest-5:"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	":ftest-6:"
}
expect {
	timeout {puts "TESTING ERROR 19\n";exit}
	":ftest-7:"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	":ftest-8:"
}
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	":ftest-9:"
}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	":ftest-"
}
after 100

send -- "firejail --shutdown=ftest-5\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	"Sending SIGTERM"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	":ftest-5:"  {puts "TESTING ERROR 15\n";exit}
	":ftest-9:"
}

after 100
puts "all done\n"
