#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=12345\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"invalid sandbox name"
}
after 100

send --  "firejail --name=\"join testing\"\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"invalid sandbox name"
}
after 100


send --  "firejail --name=join\\ testing\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"invalid sandbox name"
}
after 100

send -- "firejail --name=asdf,12345\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"invalid sandbox name"
}
after 100


send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --list\r"
expect {
	timeout {puts "TESTING ERROR 17\n";exit}
	":ftest:"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 19\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 25\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 26\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 27\n";exit}
	":ftest-"
}
expect {
	timeout {puts "TESTING ERROR 28\n";exit}
	":ftest-"
}
sleep 1
puts "all done\n"
