#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --name=ftest\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

spawn $env(SHELL)
send -- "firejail --profile.print=ftest\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/etc/firejail/default.profile"
}


after 100
puts "all done\n"
