#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --name=test\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send -- "firejail --seccomp.print=test\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"ld  data.syscall-number"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"jeq delete_module"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"jeq init_module"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"ret ALLOW"
}
after 100
puts "\nall done\n"
