#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

set firstspawn $spawn_id

send --  "firejail --name=shutdowntesting ./catchsignal.sh\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send --  "firejail --shutdown=shutdowntesting\r"

set spawn_id $firstspawn
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"2"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"3"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"4"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"5"
}
after 100

puts "\nalldone\n"
