#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 15
cd /home
spawn $env(SHELL)
match_max 100000

send --  "firejail --name=shutdowntesting\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 2

spawn $env(SHELL)
send -- "stty -echo\r"
after 100
send --  "firejail --shutdown=shutdowntesting; echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"done"
}
sleep 5

spawn $env(SHELL)
send --  "firejail --list;echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"shutdowntesting" {puts "TESTING ERROR 3\n";exit}
	"done"
}
sleep 1

send --  "firejail --shutdown=sutdowntesting\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"cannot find sandbox sutdowntesting"
}
after 100

send --  "firejail --shutdown=1\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Error: no valid sandbox"
}
after 100

puts "\nall done\n"
