#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100

spawn $env(SHELL)
send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --tree\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 3.1\n";exit}
	":/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 4.1\n";exit}
	":/bin/bash"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 5.1\n";exit}
	":/bin/bash"
}
after 100


puts "\n"
