.SUFFIXES:
ROOT = ../..
-include $(ROOT)/config.mk

MOD = etc-cleanup
MOD_DIR = $(ROOT)/src/$(MOD)
PROG = $(MOD_DIR)/$(MOD)
TARGET = $(PROG)

EXTRA_HDRS = ../include/etc_groups.h

include $(ROOT)/src/prog.mk
