.SUFFIXES:
ROOT = ../..
-include $(ROOT)/config.mk

MOD_DIR = src/fcopy
PROG = fcopy
TARGET = $(PROG)

EXTRA_HDRS = ../include/common.h ../include/syscall.h
EXTRA_OBJS = ../lib/common.o

include $(ROOT)/src/prog.mk
