#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --overlay-clean\r"
after 100
send -- "file ~/.firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"cannot open"
}
after 100

send -- "firejail --overlay-tmpfs\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"not available for kernels older than 3.18" {puts "\nTESTING: overlayfs not available\n"; exit}
	"Error: --overlay option is not available on Grsecurity systems" {puts "\nTESTING: overlayfs not available\n"; exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "found\n"}
}
sleep 1
send -- "stty -echo\r"
after 100

send -- "echo xyzxyzxyz > ~/_firejail_test_file; echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}
after 100

send -- "stty -echo\r"
after 100
send -- "cat  ~/_firejail_test_file; echo done\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"xyzxyzxyz"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"done"
}
after 100

send -- "exit\r"
sleep 1

send -- "stty -echo\r"
after 100
send -- "cat  ~/_firejail_test_file; echo done\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"xyzxyzxyz" {puts "TESTING ERROR 6\n";exit}
	"done"
}
after 100

send -- "file ~/.firejail\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"cannot open"
}
after 100

puts "\nall done\n"
