#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail  --chroot=/tmp/chroot\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Error: --chroot option is not available on Grsecurity systems" {puts "\nall done\n"; exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms" {puts "chroot available\n"};
}
sleep 1

send -- "cd /\r"
after 100


send -- "./unchroot\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Operation not permitted"
}
after 100

puts "all done\n"
