#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "mkdir -p ~/fjtest-dir/fjtest-dir\r"
after 100
send -- "mkdir /tmp/fjtest-dir\r"
after 100

if { ! [file exists ~/fjtest-dir/fjtest-dir] } {
	puts "TESTING ERROR 1\n"
	exit
}
if { ! [file exists /tmp/fjtest-dir] } {
	puts "TESTING ERROR 2\n"
	exit
}

send -- "firejail --noprofile --tmpfs=~/fjtest-dir\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "ls ~/fjtest-dir/fjtest-dir\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"No such file or directory"
}
after 500

send -- "exit\r"
after 500

send -- "firejail --noprofile --tmpfs=/tmp/fjtest-dir\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Warning: you are not allowed to mount a tmpfs"
}
after 500

# cleanup
send -- "rm -fr ~/fjtest-dir\r"
after 100
send -- "rm -fr /tmp/fjtest-dir\r"
after 100


puts "\nall done\n"
