#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000



# file link
#send -- "firejail --private=fscheck-file-link\r"
#expect {
#	timeout {puts "TESTING ERROR 2\n";exit}
#	"Error"
#}
#after 100

# file
send -- "firejail --private=testfile1\r"
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"Error"
}
after 100

# ..
send -- "firejail --private=../fs/testfile1\r"
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"Error"
}
after 100

# no file
send -- "firejail --private=../test/nodir\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Error"
}
after 100

# same owner
send -- "firejail --private=/etc\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Error"
}
after 100

puts "\nall done\n"
