#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --ignore=private-dev\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "cat /dev/kmsg\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Permission denied"
}
after 100

send -- "cat /proc/kmsg\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Permission denied"
}
after 100

puts "\nall done\n"
