#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 3
spawn $env(SHELL)
match_max 100000


send -- "firejail --profile=./macro-whitelist.profile ls ~\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Desktop"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Documents"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Downloads"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Music"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Pictures"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Videos"
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Desktop; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 8.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Documents; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 10\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 10.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Downloads; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 11\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 12\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 12.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Music; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 13\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 14\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 14.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Pictures; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 15\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 16\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 16.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-blacklist.profile ls ~/Videos; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 17\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 18\n";exit}
	"Permission denied" {}
	-re {ret 0} {puts "TESTING ERROR 18.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Desktop/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 19\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 20\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 20.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Documents/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 21\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 22\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 22.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Downloads/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 23\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 24\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 24.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Music/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 25\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 26\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 26.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Pictures/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 27\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 28\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 28.1\n";exit}
}
after 100

send -- "firejail --profile=./macro-readonly.profile touch ~/Videos/_firejail_test_file; echo ret \$?\r"
expect {
	timeout {puts "TESTING ERROR 29\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
expect {
	timeout {puts "TESTING ERROR 30\n";exit}
	"Read-only file system" {}
	-re {ret 0} {puts "TESTING ERROR 30.1\n";exit}
}
after 100

puts "\nall done\n"
