#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2019 Firejail Authors
# License GPL v2

set timeout 3
spawn $env(SHELL)
match_max 100000

send -- "firejail --profile=mkdir.profile find ~/.firejail_test\r"
expect {
	timeout {puts "TESTING ERROR 1.1\n";exit}
	"Warning: cannot create" { puts "TESTING ERROR 1.2\n";exit}
	"No such file or directory" { puts "TESTING ERROR 1.3\n";exit}
	".firejail_test/a/b/c/d.txt"
}
send -- "rm -rf ~/.firejail_test\r"
after 100

send -- "firejail --profile=mkdir2.profile\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"only directories in user home or /tmp"
}
after 100

puts "\nall done\n"
