#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


# testing profile and private
send -- "firejail --private --profile=mkdir_mkfile.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "find ~ | LC_ALL=C sort\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"_firejail_test_dir"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"_firejail_test_dir/dir1"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"_firejail_test_dir/dir1/dir2"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"_firejail_test_dir/dir1/dir2/dir3"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"_firejail_test_dir/dir1/dir2/dir3/file1"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"_firejail_test_file"
}
after 100
send -- "exit\r"
after 100

send -- "firejail --profile=mkfile.profile\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"only files or directories in user home, /tmp"
}
after 100

puts "all done\n"
