#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000
set PWD $env(PWD)


send -- "firejail --noprofile --noblacklist=$PWD --blacklist=$PWD --noexec=$PWD\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls $PWD\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"noblacklist-blacklist-noexec.exp"
}
after 100

send -- "$PWD/noblacklist-blacklist-noexec.exp\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Permission denied"
}
after 100

send -- "exit\r"
sleep 1

puts "\nall done\n"
