#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --noprofile --noblacklist=~ --blacklist=~ --read-only=~\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls ~\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Downloads"
}
after 100

send -- "echo World > ~/Hello\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Read-only file system"
}
after 100

send -- "exit\r"
sleep 1

puts "\nall done\n"
