#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --blacklist=/etc/passwd\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "cat /etc/passwd;echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}
after 100

puts "\n"
