#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "mkdir ~/_firejail_test_dir\r"
after 100
send -- "touch ~/_firejail_test_dir/a\r"
after 100

send -- "firejail --blacklist=/etc/passwd --blacklist=~/_firejail_test_dir\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "cat /etc/passwd;echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}
after 100
send -- "cat ~/_firejail_test_dir/a;echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}
after 100

send -- "exit\r"
sleep 1

send -- "rm -fr ~/_firejail_test_dir\r"
after 100

puts "\nall done\n"
