#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --blacklist=/var\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100
send -- "stty -echo\r"

send -- "ls -l /var;echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}
send -- "cd /var;echo done\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Permission denied"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"done"
}
after 100

puts "\nall done\n"
