#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private-etc=blablabla\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /etc | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0" {puts "Debian\n"}
	"1" {puts "Arch\n"}
}
send -- "exit\r"
sleep 1

send -- "firejail --profile=private-etc-empty.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /etc | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0" {puts "Debian\n"}
	"1" {puts "Arch\n"}

}

after 100
puts "\nall done\n"
