#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "mkdir --mode=700 ~/.cache\r"
after 500

send -- "touch ~/.cache/abcdefg\r"
after 500

if { ! [file exists ~/.cache/abcdefg] } {
	puts "TESTING ERROR 0\n"
	exit
}

send -- "firejail --noprofile --private-cache\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -l ~/.cache\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"total 0"
}
after 100

send -- "exit\r"
sleep 1

# cleanup
send -- "rm ~/.cache/abcdefg\r"
after 100

puts "\nall done\n"
