#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private --whitelist=/tmp/.X11-unix\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 100

send -- "ls -al /tmp\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	".X11-unix"
}
after 100

send -- "ls -a /tmp | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"3"
}
after 100

send -- "ls -a ~ | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"3" {puts "3\n"}
	"4" {puts "4\n"}
	"5" {puts "5\n"}
	"6" {puts "6\n"}
}

sleep 1
puts "\nall done\n"
