#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


if {[file exists ~/.asoundrc]} {
	puts "found .asoundrc file\n"
} else {
	send -- "touch ~/.asoundrc\r"
}
after 100

if {[file exists ~/.Xauthority]} {
	puts "found .Xauthority file\n"
} else {
	send -- "touch ~/.Xauthority\r"
}
after 100

# testing profile and private
send -- "firejail --private\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -l ~\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"total 0"
}
after 100

send -- "find ~ | LC_ALL=C sort\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	".Xauthority"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	".asoundrc"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	".bashrc"
}
after 100

send -- "exit\r"
sleep 1

puts "all done\n"
