#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "firejail --private-etc=blablabla\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /etc | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0"
}
send -- "exit\r"
sleep 1

send -- "firejail --profile=private-etc-empty.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "ls -l /etc | wc -l\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0"
}

after 100
puts "\nall done\n"
