#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2022 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --private=~\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100

send -- "ls -l ~\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"total 0"
}
after 100

puts "\nall done\n"
