#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

# create some test files in user home directory
send -- "touch ~/_firejail_test_file1\r"
send -- "touch ~/_firejail_test_file2\r"
send -- "mkdir ~/_firejail_test_dir1\r"
send -- "mkdir ~/_firejail_test_dir1/_firejail_test_dir2\r"
send -- "touch ~/_firejail_test_dir1/_firejail_test_dir2/_firejail_test_file3\r"
after 100

send -- "firejail --private-home=_firejail_test_file1,_firejail_test_file2,_firejail_test_dir1\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
after 100

send -- "find ~\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"_firejail_test_file3"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"_firejail_test_file2"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"_firejail_test_file1"
}
after 100

send -- "rm -f ~/_firejail_test_file*\r"
send -- "rm -fr ~/_firejail_test_dir*\r"
after 100

puts "\nall done\n"

