#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000


send -- "firejail --read-only=~/_firejail_test_dir --read-write=~/_firejail_test_dir/test1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "echo mytest >~/_firejail_test_dir/a;echo done\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"done"
}

send -- "echo mytest >~/_firejail_test_dir/test1/b;echo done\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"done"
}

send -- "cat ~/_firejail_test_dir/a;echo done\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"mytest" {puts "TESTING ERROR 4\n";exit}
	"done"
}


send -- "cat ~/_firejail_test_dir/test1/b;echo done\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"mytest"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"done"
}

after 100
puts "\nall done\n"
