#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2026 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --tmpfs=/var\r"
expect {
        timeout {puts "TESTING ERROR 1\n";exit}
        -re "you are not allowed to mount a tmpfs" {puts "TESTING ERROR 2\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "ls /var/tmp\r"
expect {
        timeout {puts "TESTING ERROR 3\n";exit}
	-re "cannot access"
}
after 100

send -- "exit\r"
after 500

send -- "firejail --profile=./tmpfs.profile\r"
expect {
        timeout {puts "TESTING ERROR 4\n";exit}
        -re "you are not allowed to mount a tmpfs" {puts "TESTING ERROR 5\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
after 500

send -- "ls /var/tmp\r"
expect {
        timeout {puts "TESTING ERROR 3\n";exit}
	-re "cannot access"
}
after 100

send -- "exit\r"
after 100

puts "\nall done\n"
