#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "echo 123 > /tmp/_firejail_test_file\r"
sleep 1

send -- "firejail --whitelist=/tmp/_firejail_test_file --whitelist=/tmp/_firejail_test_file\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "cat /tmp/_firejail_test_file\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"123"
}

send -- "exit\r"
sleep 1

send -- "cat /tmp/_firejail_test_file\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"123"
}

send -- "rm -v /tmp/_firejail_test_file\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"removed"
}
after 100

puts "\nall done\n"
