#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2024 Firejail Authors
# License GPL v2

set timeout 30
spawn $env(SHELL)
match_max 100000

send -- "firejail --whitelist=~/blablabla --whitelist=/tmp/blablabla --whitelist=/media/blablabla --whitelist=/var/blablabla --whitelist=/opt/blablabla\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	-re "Child process initialized in \[0-9\]+.\[0-9\]+ ms"
}
sleep 1

send -- "ls -l ~\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0"
}

send -- "ls -l /tmp\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"0"
}

send -- "ls -l /media\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"0"
}

send -- "ls -l /var\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"0"
}

send -- "ls -l /dev\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"0"
}
send -- "ls -l /opt\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"0"
}

after 100

puts "\nall done\n"
