#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2016 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "cp user-dirs.dirs /tmp/.\r"
after 100

send -- "firejail --private --noprofile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
after 100

send -- "firejail --force --profile=/etc/firejail/firefox.profile\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"cannot whitelist Downloads directory"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
after 100

send -- "exit\r"
after 100

send -- "cp /tmp/user-dirs.dirs ~/.config/.\r"
after 100

send -- "firejail --force --profile=/etc/firejail/firefox.profile\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"cannot whitelist Downloads directory"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Child process initialized"
}
after 100

puts "\nall done\n"

