#!/usr/bin/expect -f
# This file is part of Firejail project
# Copyright (C) 2014-2021 Firejail Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "echo 123 > /tmp/firejal-deleteme\r"
sleep 1

send -- "firejail --whitelist=/tmp/firejal-deleteme --whitelist=/tmp/firejal-deleteme\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

send -- "cat /tmp/firejal-deleteme\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"123"
}

send -- "exit\r"
sleep 1

send -- "cat /tmp/firejal-deleteme\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"123"
}

send -- "rm -v /tmp/firejal-deleteme\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"removed"
}
after 100

puts "\nall done\n"
