.SUFFIXES:
ROOT = ../..
-include $(ROOT)/config.mk

MOD = fzenity
MOD_DIR = $(ROOT)/src/$(MOD)
PROG = $(MOD_DIR)/$(MOD)
TARGET = $(PROG)

EXTRA_HDRS = ../include/common.h

include $(ROOT)/src/prog.mk
