ROOT = ../..
-include $(ROOT)/config.mk

PROG = fsec-print
TARGET = $(PROG)

MOD_HDRS = ../include/common.h ../include/seccomp.h ../include/syscall.h
MOD_OBJS = ../lib/common.o ../lib/errno.o ../lib/syscall.o

include $(ROOT)/src/common.mk
