# Checks that `make dist` works and builds the project with the default
# configuration.

name: Build

# Note: Keep this list in sync with DISTFILES in ../../Makefile.
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '**'
    paths:
      - 'contrib/**'
      - 'etc/**'
      - 'm4/**'
      - 'platform/**'
      - 'src/**'
      - 'test/**'
      - 'ci/check/release-version.sh'
      - .github/workflows/build.yml
      - COPYING
      - Makefile
      - README
      - RELNOTES
      - ci/printenv.sh
      - config.mk.in
      - config.sh.in
      - configure
      - configure.ac
      - mkdeb.sh
      - testcompile.sh
  pull_request:
    paths:
      - 'contrib/**'
      - 'etc/**'
      - 'm4/**'
      - 'platform/**'
      - 'src/**'
      - 'test/**'
      - 'ci/check/release-version.sh'
      - .github/workflows/build.yml
      - COPYING
      - Makefile
      - README
      - RELNOTES
      - ci/printenv.sh
      - config.mk.in
      - config.sh.in
      - configure
      - configure.ac
      - mkdeb.sh
      - testcompile.sh

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: print env
      run: ./ci/printenv.sh
    - name: check release version
      if: github.ref_type == 'tag'
      env:
        RELEASE_TAG: ${{ github.ref_name }}
      run: ./ci/check/release-version.sh "$RELEASE_TAG" configure.ac
    - name: configure
      run: >
        ./configure
        --prefix=/usr --enable-fatal-warnings
        --disable-apparmor --disable-selinux
        || (cat config.log; exit 1)
    - name: make
      run: make -j "$(nproc)" -Orecurse
    - name: make install
      run: sudo make install
    - name: make installcheck
      run: make installcheck
